### ISSUE TITLE
Problems connecting to MySql

### ISSUE THREAD

**Issue by Vayunee** [SkinsRestorer/SkinsRestorerX#1009]
Hi, I can't use mysql with SkinsRestorer (Bungee). The error is:
```
[16:56:56 WARN] [net.skinsrestorer.shadow.mariadb.message.server.ErrorPacket]: Error: 1044-42000: Access denied for user 'SkinsRestorer'@'localhost' to database 'SkinsRestorer'
[16:56:56 ERROR] [net.skinsrestorer.shadow.mariadb.pool.Pool]: error initializing pool connection
java.sql.SQLSyntaxErrorException: (conn=1324) Access denied for user 'SkinsRestorer'@'localhost' to database 'SkinsRestorer'
        at net.skinsrestorer.shadow.mariadb.export.ExceptionFactory.createException(ExceptionFactory.java:280) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.export.ExceptionFactory.create(ExceptionFactory.java:368) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:301) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.<init>(StandardClient.java:188) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.Driver.connect(Driver.java:70) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.pool.Pool.addConnection(Pool.java:197) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.pool.Pool.<init>(Pool.java:99) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.pool.Pools.retrievePool(Pools.java:36) ~[?:?]
        at net.skinsrestorer.shadow.mariadb.MariaDbPoolDataSource.<init>(MariaDbPoolDataSource.java:43) ~[?:?]
        at net.skinsrestorer.shared.storage.MySQL.connectPool(MySQL.java:79) ~[?:?]
        at net.skinsrestorer.shared.utils.SharedMethods.initMysql(SharedMethods.java:76) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.initStorage(SkinsRestorer.java:165) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:131) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
```

**Comment by xknat** [comment]
For support, please join our discord.
This does not look like a bug but rather to little permissions given to the mysql user
