### ISSUE TITLE
mysql init issue on velocity

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1053]
Ticket: ticket-1661610511
SkinsRestorer version: v14.2.4-SNAPSHOT
ProxyMode: Velocity-Plugin
Server: 3.1.2-SNAPSHOT (git-6496983c-b171)
[14:27:16 ERROR]: Exception in task net.skinsrestorer.shared.commands.ISkinCommand$$Lambda$2192/0x0000000801612988@597e5e87 by plugin SkinsRestorer
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.shared.storage.MySQL.query(String, Object[])" because "this.mysql" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinNameOfPlayer(SkinStorage.java:160) ~[?:?]
        at net.skinsrestorer.shared.commands.ISkinCommand.setSkin(ISkinCommand.java:234) ~[?:?]
        at net.skinsrestorer.shared.commands.ISkinCommand.lambda$onSkinSetOther$2(ISkinCommand.java:183) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228) ~[bin.jar:3.1.2-SNAPSHOT (git-6496983c-b171)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by xknat** [comment]
Likely already resolved in v15
