### ISSUE TITLE
Error on connect Bungeecord

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SkinsRestorer/SkinsRestorerX#109]
### Describe the problem in a few short sentences
```21:09:09 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@fd0e5b6, id=26835, owner=skinsrestorer.bungee.SkinsRestorer@47e4d9d0, task=skinsrestorer.bungee.listeners.LoginListener$1@12879454, delay=0, period=0, running=true) encountered an exception
java.lang.IllegalStateException: Plugin skinsrestorer.bungee.SkinsRestorer@47e4d9d0 has not registered intent for event LoginEvent(cancelled=false, cancelReasonComponents=null, connection=[xMokkate] <-> InitialHandler)
    at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
    at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:68)
    at skinsrestorer.bungee.listeners.LoginListener$1.run(LoginListener.java:79)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```
### How can we reproduce the problem?
by connecting
### What version of SkinsRestorerX are you using?
13.5.1
### What is your Spigot/BungeeCord/Sponge version?
1.13

**Comment by McLive** [comment]
This has been fixed in the most recent version on [Jenkins](https://ci.freecraft.eu/v2/job/SkinsRestorerX/).

#8b3efd5
