### ISSUE TITLE
org.bukkit.entity.Player.getLocale()Ljava/lang/String; not found in bukkit 1.8.8

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1130]
FlamePaper 1.8.8

[11:37:49 INFO]: Regomy issued server command: /skin killid
[11:37:49 WARN]: Exception in thread "Craft Scheduler Thread - 8"
[11:37:49 WARN]: org.apache.commons.lang.UnhandledException: Plugin SkinsRestorer v14.2.4 generated an exception while executing task 580
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getLocale()Ljava/lang/String;
at net.skinsrestorer.bukkit.utils.WrapperBukkit$2.getLocale(WrapperBukkit.java:67)
at net.skinsrestorer.shadow.aikar.locales.LocaleManager.getMessage(LocaleManager.java:84)
at net.skinsrestorer.shared.SkinsRestorerAPIShared.getMessage(SkinsRestorerAPIShared.java:53)
at net.skinsrestorer.shared.interfaces.ISRCommandSender.sendMessage(ISRCommandSender.java:28)
at net.skinsrestorer.shared.commands.ISkinCommand.setSkin(ISkinCommand.java:229)
at net.skinsrestorer.shared.commands.ISkinCommand.lambda$onSkinSetOther$2(ISkinCommand.java:182)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by xknat** [comment]
fixed in eaaf47f05bc7f1b8257820984782d8b6427bf39e
