### ISSUE TITLE
catch RSA public key is not available client side mysql error

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1138]
solution: mysql option should be `allowPublicKeyRetrieval=true&useSSL=false`

**Comment by xknat** [comment]
```
13:40:46 [SEVERE] error initializing pool connection
java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
    at net.skinsrestorer.shadow.mariadb.plugin.authentication.standard.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:141)
    at net.skinsrestorer.shadow.mariadb.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:298)
    at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.<init>(StandardClient.java:189)
    at net.skinsrestorer.shadow.mariadb.Driver.connect(Driver.java:70)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.addConnection(Pool.java:197)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.<init>(Pool.java:99)
    at net.skinsrestorer.shadow.mariadb.pool.Pools.retrievePool(Pools.java:36)
    at net.skinsrestorer.shadow.mariadb.MariaDbPoolDataSource.config(MariaDbPoolDataSource.java:63)
    at net.skinsrestorer.shadow.mariadb.MariaDbPoolDataSource.setUrl(MariaDbPoolDataSource.java:239)
    at net.skinsrestorer.shared.storage.MySQL.connectPool(MySQL.java:106)
    at net.skinsrestorer.shared.utils.SharedMethods.initStorage(SharedMethods.java:81)
    at net.skinsrestorer.shared.interfaces.ISRPlugin.initStorage(ISRPlugin.java:84)
    at net.skinsrestorer.bungee.SkinsRestorerBungee.pluginStartup(SkinsRestorerBungee.java:118)
    at net.skinsrestorer.bungee.SkinsRestorerBootstrap.onEnable(SkinsRestorerBootstrap.java:27)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
13:40:46 [SEVERE] error adding connection to pool
java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
    at net.skinsrestorer.shadow.mariadb.plugin.authentication.standard.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:141)
    at net.skinsrestorer.shadow.mariadb.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:298)
    at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.<init>(StandardClient.java:189)
    at net.skinsrestorer.shadow.mariadb.Driver.connect(Driver.java:70)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.addConnection(Pool.java:197)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.lambda$addConnectionRequest$0(Pool.java:127)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
13:40:46 [INFO] [SkinsRestorer] ----------------------------------------------
13:40:46 [INFO] [SkinsRestorer]     +==================+
13:40:46 [INFO] [SkinsRestorer]     |   SkinsRestorer  |
13:40:46 [INFO] [SkinsRestorer]     +==================+
13:40:46 [INFO] [SkinsRestorer] ----------------------------------------------
13:40:46 [INFO] [SkinsRestorer]     Current version: 14.2.4-SNAPSHOT
13:40:46 [INFO] [SkinsRestorer]     This is the latest version!
13:40:46 [INFO] [SkinsRestorer] ----------------------------------------------
13:41:16 [SEVERE] java.sql.SQLException: No connection available within the specified time (option 'connectTimeout': 30,000 ms)
13:41:16 [SEVERE]     at net.skinsrestorer.shadow.mariadb.pool.Pool.getPoolConnection(Pool.java:382)
13:41:16 [SEVERE]     at net.skinsrestorer.shadow.mariadb.MariaDbPoolDataSource.getConnection(MariaDbPoolDataSource.java:79)
13:41:16 [SEVERE]     at net.skinsrestorer.shared.storage.MySQL.execute(MySQL.java:114)
13:41:16 [SEVERE]     at net.skinsrestorer.shared.storage.MySQL.createTable(MySQL.java:45)
13:41:16 [SEVERE]     at net.skinsrestorer.shared.utils.SharedMethods.initStorage(SharedMethods.java:82)
13:41:16 [SEVERE]     at net.skinsrestorer.shared.interfaces.ISRPlugin.initStorage(ISRPlugin.java:84)
13:41:16 [SEVERE]     at net.skinsrestorer.bungee.SkinsRestorerBungee.pluginStartup(SkinsRestorerBungee.java:118)
13:41:16 [SEVERE]     at net.skinsrestorer.bungee.SkinsRestorerBootstrap.onEnable(SkinsRestorerBootstrap.java:27)
13:41:16 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
13:41:16 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)
13:41:16 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
13:41:16 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
13:41:16 [WARNING] [SkinsRestorer] MySQL error: No connection available within the specified time (option 'connectTimeout': 30,000 ms)
13:41:16 [SEVERE] error adding connection to pool
java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
    at net.skinsrestorer.shadow.mariadb.plugin.authentication.standard.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:141)
    at net.skinsrestorer.shadow.mariadb.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:298)
    at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.<init>(StandardClient.java:189)
    at net.skinsrestorer.shadow.mariadb.Driver.connect(Driver.java:70)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.addConnection(Pool.java:197)
    at net.skinsrestorer.shadow.mariadb.pool.Pool.lambda$addConnectionRequest$0(Pool.java:127)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by xknat** [comment]
We have not gotten this issue for a while now.
