### ISSUE TITLE
Plugin failed to load [MetricsLite]

### ISSUE THREAD

**Issue by JAQUBA** [SkinsRestorer/SkinsRestorerX#115]
plugin failed to load. fresh install on Waterfall 1.13.2 (lastest version) [Enabled Waterfall version git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]

lastest version of SkinsRestorer 13.5.2

[20:05:55 WARN]: Exception encountered when loading plugin: SkinsRestorer
java.lang.NoClassDefFoundError: org/bstats/bungeecord/MetricsLite
	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:69) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
Caused by: java.lang.ClassNotFoundException: org.bstats.bungeecord.MetricsLite
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 5 more

**Comment by Angel-0** [comment]
Hello, 

The wrong file was updated. My apologizes for that.

Best regards,
Angel.
