### ISSUE TITLE
zip file closed

### ISSUE THREAD

**Issue by molor** [SkinsRestorer/SkinsRestorerX#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

```
[SkinsRestorer] Plugin SkinsRestorer v14.2.8 generated an exception while executing task 24
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.skinsrestorer.shared.utils.connections.MojangAPI.readURL(MojangAPI.java:285) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.utils.connections.MojangAPI.readURL(MojangAPI.java:271) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.utils.connections.MojangAPI.getUUIDAshcon(MojangAPI.java:135) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.utils.connections.ServiceChecker.checkServices(ServiceChecker.java:47) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.utils.SharedMethods.runServiceCheck(SharedMethods.java:55) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinsRestorerBukkit.lambda$pluginStartup$7(SkinsRestorerBukkit.java:258) ~[SkinsRestorer.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-446]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-446]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### How can we reproduce what you got?

1. Start the server
2. Press `CTRL+C` after `SERVER IS RUNNING IN OFFLINE/INSECURE MODE!` is appeared so it will start to stop immediately after starting
3. See the exception

It may not appear at the first time, so try again

### Minecraft implementation

```markdown
git-Paper-446 (MC: 1.19.3, Git: 4e99466)
```

### What client are you using?

Vanilla Launcher

### SkinsRestorer Version

See `Describe your issue`

### List of plugins

Bukkit Plugins: AutoMessage, Chunky, ChunkyBorder, CoreProtect, dynmap, Essentials, EssentialsGeoIP, EssentialsSpawn, LuckPerms, MobArena, MobArena-AR, NoCheatPlus, OpenInv, Orebfuscator, ProtocolLib, SkinsRestorer, Vault, WorldEdit, WorldGuard

### Java Version

17.0.3

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Will be fixed by v15.

**Comment by AlexProgrammerDE** [comment]
Should be resolved by v15.
