### ISSUE TITLE
Error on player quit

### ISSUE THREAD

**Issue by Matocolotoe** [SkinsRestorer/SkinsRestorerX#123]
### what SkinsRestorer version are you using? (make sure its latest!)
Latest version

### Describe the problem in a few short sentences
This prints in console everytime a player disconnects (example below)
```
[12:24:40] [Craft Scheduler Thread - 329/WARN]: [SkinsRestorer] Failed to get resource info from spiget.org
java.io.IOException: Server returned HTTP response code: 504 for URL: http://api.spiget.org/v2/resources/2124/versions/latest?ut=1554805419863
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_201]
	at skinsrestorer.shared.utils.UpdateChecker.checkForUpdate(UpdateChecker.java:48) ~[?:?]
	at skinsrestorer.bukkit.SkinsRestorer.lambda$checkUpdate$6(SkinsRestorer.java:207) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [Spigot-v1_8_8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

### What is your Spigot/BungeeCord/Sponge version?
Spigot 1.8.8

**Comment by Mc-muffin** [comment]
I confirm this issue also occurs to me with Skinsrestorer v13.6.1 on spigot 1.13.2-R0.1-SNAPSHOT (git-spigot-f09662d-f40143e)

**Comment by Angel-0** [comment]
Hello,

This is not a SkinsRestorer error, nor a Spigot/Bukkit error, but a Spiget error. Spiget is the tool used to check if there are new updates. We can't do anything except waiting.

Regards, Angel, _admin of Discord consecrated to SkinsRestorer_

**Comment by xknat** [comment]
see https://status.spiget.org/ 
also https://status.spiget.org/782124312
![image](https://user-images.githubusercontent.com/10220139/55795255-a41f0980-5ac7-11e9-9891-0074e937350b.png)
