### ISSUE TITLE
v15 command blocks async sendSystemMessage error

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#1262]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

[15:04:11 ERROR]: Thread Craft Scheduler Thread - 22 - SkinsRestorer failed main thread check: sendSystemMessage to a command block
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.world.level.BaseCommandBlock.sendSystemMessage(BaseCommandBlock.java:175) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:32) ~[paper-1.19.4.jar:git-Paper-510]
        at net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:46) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:51) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:184) ~[SkinsRestorer.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at net.skinsrestorer.shared.commands.library.CommandManager.lambda$registerParameters$7(CommandManager.java:242) ~[SkinsRestorer.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-510]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[15:04:11 WARN]: java.lang.reflect.InvocationTargetException
[15:04:11 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[15:04:11 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:04:11 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.library.CommandManager.lambda$registerParameters$7(CommandManager.java:242)
[15:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:04:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:04:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:04:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:04:11 WARN]: Caused by: java.lang.IllegalStateException: Asynchronous sendSystemMessage to a command block!
[15:04:11 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[15:04:11 WARN]:        at net.minecraft.world.level.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:175)
[15:04:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:32)
[15:04:11 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:46)
[15:04:11 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:51)
[15:04:11 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209)
[15:04:11 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:184)
[15:04:11 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:04:11 WARN]:        ... 8 more
[15:04:15 INFO]: xknat lost connection: Disconnected
[15:04:15 INFO]: xknat left the game
[15:04:15 INFO]: UUID of player xknat is 8f348d4a-7cb9-331f-b782-fa2562a4adcc
[15:04:15 INFO]: xknat joined the game
[15:04:15 INFO]: xknat[/127.0.0.1:55749] logged in with entity id 1328 at ([world]-70.49466943640938, 78.0, 62.77066400904214)
[15:04:19 ERROR]: Thread Craft Scheduler Thread - 23 - SkinsRestorer failed main thread check: sendSystemMessage to a command block
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.world.level.BaseCommandBlock.sendSystemMessage(BaseCommandBlock.java:175) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:32) ~[paper-1.19.4.jar:git-Paper-510]
        at net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:46) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:51) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:184) ~[SkinsRestorer.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at net.skinsrestorer.shared.commands.library.CommandManager.lambda$registerParameters$7(CommandManager.java:242) ~[SkinsRestorer.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-510]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[15:04:19 WARN]: java.lang.reflect.InvocationTargetException
[15:04:19 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[15:04:19 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[15:04:19 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.library.CommandManager.lambda$registerParameters$7(CommandManager.java:242)
[15:04:19 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:04:19 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:04:19 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:04:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:04:19 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:04:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:04:19 WARN]: Caused by: java.lang.IllegalStateException: Asynchronous sendSystemMessage to a command block!
[15:04:19 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[15:04:19 WARN]:        at net.minecraft.world.level.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:175)
[15:04:19 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:32)
[15:04:19 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:46)
[15:04:19 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.bukkit.wrapper.WrapperCommandSender.sendMessage(WrapperCommandSender.java:51)
[15:04:19 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209)
[15:04:19 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:184)
[15:04:19 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[15:04:19 WARN]:        ... 8 more

**Comment by AlexProgrammerDE** [comment]
Resolved by https://github.com/SkinsRestorer/SkinsRestorerX/commit/8551122dedd2534c0f9c8c1c3d80fd30120c56d7
