### ISSUE TITLE
Add support for ArcLight Server

### ISSUE THREAD

**Issue by Gabbonet** [SkinsRestorer/SkinsRestorerX#1274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [x] I have read the installation guide and performed all steps

### Describe your issue

I am getting a "WARN" message on my server console every second. My server is "ArcLight" (Mod + Plugins) version 1.16.5. with 40 mods. 

The server works perfectly with all 40 mods. The first plugin I decided to put was SkinRestorer, and that's when I get this message in the console. When I remove the plugin the message stops appearing, so it's because of the plugin.

It should be noted that the server works perfectly, there are no problems of any kind when playing and the skins look perfectly, but it seems to me that it is not normal for this very long message to appear on the console every 1 second.
![imagen_2023-05-22_111816556](https://github.com/SkinsRestorer/SkinsRestorerX/assets/118401053/ee79ea13-76de-47fa-986d-575282e95113)
![imagen_2023-05-22_111922784](https://github.com/SkinsRestorer/SkinsRestorerX/assets/118401053/69b33161-1508-4218-996f-18fefaccdef4)

The message is this:

[17:04:46] [Server thread/WARN] [SkinsRestorer/]: Task #6 for SkinsRestorer v14.2.10 generated an exception
java.lang.NoClassDefFoundError: Lnet/minecraft/client/renderer/model/RenderMaterial;
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.tryDefineClass(ClassLoaderRemapper.java:183) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.tryGetFields(ClassLoaderRemapper.java:165) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.lambda$getFields$1(ClassLoaderRemapper.java:144) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading}
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_312] {}
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.getFields(ClassLoaderRemapper.java:144) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.tryMapFieldToSrg(ClassLoaderRemapper.java:218) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading}
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.handleClassGetField(ArclightReflectionHandler.java:191) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {}
        at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_0.handleClassGetDeclaredField(ArclightReflectionHandler.java:202) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {}
        at net.skinsrestorer.shadow.aikar.commands.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:325) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_312] {}
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_312] {}
        at net.skinsrestorer.shadow.aikar.commands.BukkitCommandManager.lambda$new$1(BukkitCommandManager.java:138) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.handler$bbi000$arclight$runScheduler(MinecraftServerMixin.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

### How can we reproduce what you got?

ArcLight server with 40 mods working perfectly, I just added a single SkinRestore plugin and I get that annoying message

### Server/Error Logs

https://gist.github.com/Gabbonet/52cc78eb19db56e5e2a71a24e54d84ec#file-warn-skinsrestorer-generated-an-exception-txt

### Minecraft implementation

```markdown
- Proxy: 
- Backend:
```

### What client are you using?

Minecraft Original

### SkinsRestorer Version

14.2.10

### List of plugins

SkinsRestorer (Only)

### Java Version

17

### Does your issue require a plugin in order to reproduce?

No

**Comment by Gabbonet** [comment]
I fixed it, the error was the java version. I was using a very old version of Java, specifically I was using version 6. (For some reason the page didn't install the java that I had selected, which was version 17). I installed the version of Java 17 and the messages stopped appearing. that was the solution

**Comment by Gabbonet** [comment]
I fixed it, the error was the java version. I was using a very old version of Java, specifically I was using version 6. (For some reason the page where I host the server didn't install the java that I had selected, which was version 17). I installed the version of Java 17 and the messages stopped appearing. that was the solution
