### ISSUE TITLE
An exception occurred while executing event SkinApplyEventImpl for subscriber org.geysermc.floodgate.event.EventSubscriber

### ISSUE THREAD

**Issue by Brasil150** [SkinsRestorer/SkinsRestorerX#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Backend error when activating Floodgate-send-data on the Proxy. Error occurs when trying to log into the server.
Proxy: Waterfall
Backend: Paper 1.12.2

[00:18:17 ERROR]: [org.geysermc.floodgate.event.EventBus] An exception occurred while executing event SkinApplyEventImpl for subscriber org.geysermc.floodgate.event.EventSubscriber
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.shared.storage.adapter.StorageAdapter.getPlayerData(java.util.UUID)" because the return value of "net.skinsrestorer.shared.storage.adapter.AdapterReference.get()" is null
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinIdOfPlayer(PlayerStorageImpl.java:52) ~[?:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:113) ~[?:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:109) ~[?:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:43) ~[?:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:32) ~[?:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[?:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fireSilently(EventBusImpl.java:37) ~[?:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[?:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fire(EventBusImpl.java:37) ~[?:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:85) ~[?:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[?:?]
        at org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[?:?]
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[?:?]
        at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[?:?]
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[?:?]
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[?:?]
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[?:?]
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### How can we reproduce what you got?

1. Enable floodgate-send-data on the proxy side.
2. Install floodgate on the 1.12.2 backend
3. Reboot
4. Try joining.

### Minecraft implementation

```markdown
- Proxy: Waterfall
- Backend: Paper 1.12.2
```

### SkinsRestorer Version

15.0.7

### List of plugins

SkinsRestorer, floodgate

### Java Version

JDK 17

### Does your issue require a plugin in order to reproduce?

Yes

**Comment by typicalsmc** [comment]
im getting this issue too

**Comment by xknat** [comment]
Any update on this? can you try our dev build?
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/

@TypicalShavonne @Brasil150

**Comment by xknat** [comment]
should be resolved by https://github.com/SkinsRestorer/SkinsRestorer/commit/0af8408c6ef45c23a70169efedf54818612e206c
If not, let me know and i will reopen this issue

**Comment by Brasil150** [comment]
> Any update on this? can you try our dev build? https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/
> 
> @TypicalShavonne @Brasil150

Builds are broken in 1.12.2. Impossible to test.

**Comment by Brasil150** [comment]
`[16:02:53] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.0.14-SNAPSHOT
[16:02:53] [Server thread/ERROR]: An unexpected error occurred while starting the plugin. Please check the console for more details.
java.lang.NoClassDefFoundError: xyz/wagyourtail/jvmdg/j16/stub/java_base/J_L_Record
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:155) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:118) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[dionysus.jar:git-Dionysus-899c2f4]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at net.skinsrestorer.shadow.injector.utils.ReflectionUtils.safeGetDeclaredMethods(ReflectionUtils.java:165) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.StandardInjectionProvider.validateHasNoInjectMethods(StandardInjectionProvider.java:156) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.StandardInjectionProvider.validateInjection(StandardInjectionProvider.java:142) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.DefaultInjectionProvider.validateInjection(DefaultInjectionProvider.java:37) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.StandardInjectionProvider.safeGet(StandardInjectionProvider.java:43) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.DefaultInjectionProvider.safeGet(DefaultInjectionProvider.java:32) ~[?:?]
	at net.skinsrestorer.shadow.injector.handlers.instantiation.DirectInstantiationProvider.resolve(DirectInstantiationProvider.java:19) ~[?:?]
	at net.skinsrestorer.shadow.injector.InjectorImpl.findResolutionOrFail(InjectorImpl.java:227) ~[?:?]
	at net.skinsrestorer.shadow.injector.InjectorImpl.resolveContext(InjectorImpl.java:153) ~[?:?]
	at net.skinsrestorer.shadow.injector.InjectorImpl.resolve(InjectorImpl.java:133) ~[?:?]
	at net.skinsrestorer.shadow.injector.InjectorImpl.getSingleton(InjectorImpl.java:72) ~[?:?]
	at net.skinsrestorer.shared.plugin.SRBootstrapper.startPlugin(SRBootstrapper.java:47) ~[?:?]
	at net.skinsrestorer.bukkit.SRBukkitBootstrap.onEnable(SRBukkitBootstrap.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:398) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[dionysus.jar:git-Dionysus-899c2f4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:227) ~[dionysus.jar:git-Dionysus-899c2f4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:630) ~[dionysus.jar:git-Dionysus-899c2f4]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: xyz.wagyourtail.jvmdg.j16.stub.java_base.J_L_Record
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[dionysus.jar:git-Dionysus-899c2f4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[dionysus.jar:git-Dionysus-899c2f4]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 33 more`

**Comment by xknat** [comment]
Ah thank you.
Can you try this build: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/1045/artifact/build/libs/SkinsRestorer.jar

**Comment by Brasil150** [comment]
Same thing as before.

It's not today that compilations are broken. I also used to use the CI builds in production, but now I'm just using the latest one from spigot.

> Ah thank you. Can you try this build: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/1045/artifact/build/libs/SkinsRestorer.jar

**Comment by xknat** [comment]
Alright thank you, please use the update then when it comes.
Fort now we have no indication that this issue is not resolved

**Comment by BySwiizen** [comment]
I have the same problem here with build 1050

**Comment by BySwiizen** [comment]
I have the same compilation problem with build 1050.

**Comment by xknat** [comment]
@BySwiizen as mentioned above, try build 1045

**Comment by BySwiizen** [comment]
> @BySwiizen as mentioned above, try build 1045

I have the same problem.

**Comment by wcdfilll** [comment]
I have the same problem.

```
[21:03:55 ERROR]: [org.geysermc.floodgate.event.EventBus] An exception occurred while executing event SkinApplyEventImpl for subscriber org.geysermc.floodgate.event.EventSubscriber
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.shared.storage.adapter.StorageAdapter.getPlayerData(java.util.UUID)" because the return value of "net.skinsrestorer.shared.storage.adapter.AdapterReference.get()" is null
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinIdOfPlayer(PlayerStorageImpl.java:51) ~[SkinsRestorer (3).jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:112) ~[SkinsRestorer (3).jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:108) ~[SkinsRestorer (3).jar:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:43) ~[SkinsRestorer (3).jar:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:32) ~[SkinsRestorer (3).jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fireSilently(EventBusImpl.java:37) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fire(EventBusImpl.java:37) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:85) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin(SpigotSkinApplier.java:53) ~[floodgate-spigot (3).jar:?]
        at org.geysermc.floodgate.skin.SkinUploadSocket.onMessage(SkinUploadSocket.java:120) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:963) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:887) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) ~[floodgate-spigot (3).jar:?]
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) ~[floodgate-spigot (3).jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mzrtamp** [comment]
Me too https://github.com/GeyserMC/Geyser/issues/4745
