### ISSUE TITLE
Annoying stack dump on skin load

### ISSUE THREAD

**Issue by katanya04** [SkinsRestorer/SkinsRestorerX#1558]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

I noticed recently, maybe after last version, that in my 1.8.8 paper server, everytime a skin is loaded, the following stack dump appears:

`[SkinsRestorer] Failed to send custom packet via ViaVersion, falling back to default method.
java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.WorldServer.isFlatWorld()
        at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_312]
        at net.skinsrestorer.shared.utils.ReflectionUtil.getMethod(ReflectionUtil.java:121) ~[?:?]
        at net.skinsrestorer.shared.utils.ReflectionUtil.invokeObjectMethod(ReflectionUtil.java:220) ~[?:?]
        at net.skinsrestorer.bukkit.refresher.SpigotSkinRefresher.refresh(SpigotSkinRefresher.java:237) ~[?:?]
        at net.skinsrestorer.bukkit.SkinApplierBukkit.applySkinSync(SkinApplierBukkit.java:95) ~[?:?]
        at net.skinsrestorer.bukkit.SkinApplierBukkit.lambda$applySkin$0(SkinApplierBukkit.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]`

Every single time. It's really annoying, I don't know if it qualifies as a bug since it still works, it justs uses that default method that is talked about in the first line of the stack dump, but I don't think its necessary to dump the stack every time because of this... It gets my logs full of these. I don't think this happened before.

**Comment by xknat** [comment]
Resolved by 2713629e025f8cd8d20dd66e482c126d2da74849 thanks for reporting
