### ISSUE TITLE
Error getting Eclipse Profile

### ISSUE THREAD

**Issue by AIGLE25** [SkinsRestorer/SkinsRestorerX#1582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

error eclipse

### How can we reproduce what you got?

put the plugin in the server and run it 

### Server/Error Logs

https://pastebin.com/KsDvKYev

### Minecraft implementation

```markdown
1.8.9 paper
Windows10
8gb for server
```

### What client are you using?

feather client , lunar client

### SkinsRestorer Version

15.0.11

### List of plugins

Plugins (46): PrivateGames, WorldEdit, Hit-Reg-Changer, SlimeWorldManager, PlaceholderAPI, Bedwars1058-Discord, BedWars1058-WinStreak, SGM4_Damaging_Snowballs, WorldGuard, Bouncer, NewAmazingLuckyBlocks, KillYourself, ViaVersion, EnderSpawn, LuckPerms, LastLoginAPI, ProtocolLib, SkinsRestorer, TAB, Vault, MessageFilter, MyCommand, Skript, DecentHolograms, BoostedAudio, AuthMe, PlayerPoints, Citizens, BedWars2023, BedWars-SpectatorOptions, ajLeaderboards, BedWars1058-AdventureMode, BedWars2023-ArenaSetup, Bedwars2023-ArenaStartMessage, CommandNPC, BedWars1058-PlayAgain, Bedwars1058-AdminAddon, BedWars2023-RewardSummary, BedWars1058-Spectate, HotbarManager, MapSelector, XpBar, Cosmetics, BedWars2023-MapCommand, BedWars2023-TeamSelector, Ultimate

### Java Version

java17

### Does your issue require a plugin in order to reproduce?

None

**Comment by Draghonir** [comment]
hi same issue for me 
![az](https://github.com/SkinsRestorer/SkinsRestorer/assets/107469643/3971ee6f-631b-4e5f-b9dd-55fedabf76d4)

**Comment by xknat** [comment]
Resolved, server hickup

**Comment by Mat1212fr** [comment]
What server hickup? I have the same issue and I just updated my Paper server to the latest stable version (# 493)
`[18:21:03 ERROR]: [SkinsRestorer] Error getting Eclipse UUID
net.skinsrestorer.shared.exception.DataRequestExceptionShared: java.io.IOException: Failed to get input stream.
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:242) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:224) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDEclipse(MojangAPIImpl.java:114) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:54) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:438) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer 15.0.11.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.io.IOException: Failed to get input stream.
        at net.skinsrestorer.shared.connections.http.HttpClient.execute(HttpClient.java:95) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:231) ~[SkinsRestorer 15.0.11.jar:?]
        ... 9 more
[18:21:09 ERROR]: [SkinsRestorer] Error getting Eclipse Profile
net.skinsrestorer.shared.exception.DataRequestExceptionShared: java.io.IOException: Failed to get input stream.
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:242) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:224) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getProfileEclipse(MojangAPIImpl.java:175) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:94) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:438) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer 15.0.11.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.io.IOException: Failed to get input stream.
        at net.skinsrestorer.shared.connections.http.HttpClient.execute(HttpClient.java:95) ~[SkinsRestorer 15.0.11.jar:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:231) ~[SkinsRestorer 15.0.11.jar:?]
        ... 9 more
`
