### ISSUE TITLE
WaterFall - errors Eclipse

### ISSUE THREAD

**Issue by Incluuu** [SkinsRestorer/SkinsRestorerX#1594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

startup waterfall

[SkinsRestorer] Error getting Eclipse UUID
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Eclipse error: 502
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDEclipse(MojangAPIImpl.java:116) ~[?:?]
        at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:54) ~[?:?]
        at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:438) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[core.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:49d41d6:576]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

[SkinsRestorer] Error getting Eclipse Profile
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Eclipse error: 502
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getProfileEclipse(MojangAPIImpl.java:177) ~[?:?]
        at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:94) ~[?:?]
        at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:438) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[core.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:49d41d6:576]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

### How can we reproduce what you got?

1. startup waterfall

### Server/Error Logs

https://bin.birdflop.com/iqumumuyiy.rb

### Minecraft implementation

```markdown
- Proxy: waterfall 1.20.6
- Backend: none
```

### What client are you using?

vanilla launcher

### SkinsRestorer Version

15.0.11

### List of plugins

SkinsRestorer

### Java Version

OpenJDK VM 21.0.3+9

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Should now be resolved.
