### ISSUE TITLE
skin not show in server 1.8 with java 17

### ISSUE THREAD

**Issue by wilywork** [SkinsRestorer/SkinsRestorerX#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

Yes

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Hi, i try set my skin and not work. 

SkinRestorer: 15.0.13
Velocity:  3.3.0-SNAPSHOT (git-1228f147-b389)
Java: 17
Core: Spigot 1.8.8

my debug log:
`[01:33:06 INFO] [skinsrestorer]: Executing command: 'skins' for 'net.skinsrestorer.velocity.wrapper.WrapperPlayer@172e5fd1'
[01:33:06 INFO] [skinsrestorer]: Executing command onDefault with method parameters [net.skinsrestorer.shared.commands.ProxyGUICommand@464e22f3, net.skinsrestorer.velocity.wrapper.WrapperPlayer@172e5fd1]
[01:33:10 INFO] [skinsrestorer]: Executing command: 'skin set Akatsuki_Member1' for 'net.skinsrestorer.velocity.wrapper.WrapperPlayer@4a61f9ab'
[01:33:10 INFO] [skinsrestorer]: Executing command onSkinSet with method parameters [net.skinsrestorer.shared.commands.SkinCommand@240b6882, net.skinsrestorer.velocity.wrapper.WrapperPlayer@4a61f9ab, Akatsuki_Member1]
[01:33:10 INFO] [skinsrestorer]: Sending GET request to https://api.mojang.com/users/profiles/minecraft/Akatsuki_Member1 with body: null
[01:33:11 WARN] [skinsrestorer]: Failed to get input stream, falling back to error stream.
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/users/profiles/minecraft/Akatsuki_Member1
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at net.skinsrestorer.shared.connections.http.HttpClient.execute(HttpClient.java:88) ~[?:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:237) ~[?:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:230) ~[?:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDMojang(MojangAPIImpl.java:126) ~[?:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:92) ~[?:?]
        at net.skinsrestorer.shared.storage.CacheStorageImpl.getUUID(CacheStorageImpl.java:68) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorageImpl.findSkinData(SkinStorageImpl.java:226) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorageImpl.findOrCreateSkinData(SkinStorageImpl.java:248) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:282) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:192) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSet(SkinCommand.java:184) ~[?:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at net.skinsrestorer.shared.commands.library.BrigadierCommand.lambda$run$0(BrigadierCommand.java:70) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[01:33:11 INFO] [skinsrestorer]: Response body: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head>    <meta content='text/html; charset=utf-8' http-equiv='content-type' />    <style type='text/css'>        body {            font-family: Arial;            margin-left: 40px;        }        img {            border: 0 none;        }        #content {            margin-left: auto;            margin-right: auto        }        #message h2 {            font-size: 20px;            font-weight: normal;            color: #000000;            margin: 34px 0px 0px 0px        }        #message p {            font-size: 13px;            color: #000000;            margin: 7px 0px 0px0px        }        #errorref {            font-size: 11px;            color: #737373;            margin-top: 41px        }    </style>    <title>Service unavailable</title></head><body>    <div id='content'>        <div id='message'>            <h2>The request is blocked.</h2>        </div>        <div id='errorref'>            <span>20240506T043310Z-r19c67c4769rfhhf86vc4ayeaw00000002y00000000062sh            </span>        </div>    </div></body></html>
[01:33:11 INFO] [skinsrestorer]: Response code: 429
[01:33:11 INFO] [skinsrestorer]: Request took 185ms.
[01:33:11 WARN] [skinsrestorer]: Received error
net.skinsrestorer.shared.exception.DataRequestExceptionShared: Please wait a minute before requesting that skin again. (Rate Limited)
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDMojang(MojangAPIImpl.java:132) ~[?:?]
        at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUID(MojangAPIImpl.java:92) ~[?:?]
        at net.skinsrestorer.shared.storage.CacheStorageImpl.getUUID(CacheStorageImpl.java:68) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorageImpl.findSkinData(SkinStorageImpl.java:226) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorageImpl.findOrCreateSkinData(SkinStorageImpl.java:248) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:282) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:209) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:192) ~[?:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSet(SkinCommand.java:184) ~[?:?]
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
        at net.skinsrestorer.shared.commands.library.BrigadierCommand.lambda$run$0(BrigadierCommand.java:70) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]
[01:33:11 INFO] [skinsrestorer]: Sending GET request to https://eclipse.skinsrestorer.net/mojang/uuid/Akatsuki_Member1 with body: null
[01:33:11 INFO] [skinsrestorer]: Response body: {"cacheData":{"state":"MISS","createdAt":1714969991544},"exists":true,"uuid":"8578e24d-3129-4e1c-a703-34510610dba5"}
[01:33:11 INFO] [skinsrestorer]: Response code: 200
[01:33:11 INFO] [skinsrestorer]: Request took 757ms.`

### Minecraft implementation

```markdown
- Proxy:
Velocity:  3.3.0-SNAPSHOT (git-1228f147-b389)
- Backend:
Core: Spigot 1.8.8
```

### What client are you using?

TLauncher

### SkinsRestorer Version

15.0.13

### List of plugins

SkinsRestorer, LuckPerms, ViaVersion, ProtocolLib, BungeeGuard

### Java Version

"17.0.10" 2024-01-16 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
old
