### ISSUE TITLE
velocity无法使用

### ISSUE THREAD

**Issue by tonyxx1** [SkinsRestorer/SkinsRestorerX#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

安装SkinsRestorer导致所有插件无法使用（包括SkinsRestorer）。安装后加载成功的插件变为了0。

### How can we reproduce what you got?

降SkinsRestorer放进插件文件夹，然后启动velocity.
velocity版本为 3.3.0-SNAPSHOT (git-1228f147-b389)

### Server/Error Logs

[22:04:55 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-1228f147-b389)... [22:04:55 INFO]: Loading localizations... [22:04:55 INFO]: Connections will use NIO channels, Java compression, Java ciphers [22:04:55 WARN]: The proxy is running in offline mode! This is a security risk and you will NOT receive any support! [22:04:55 INFO]: Loading plugins... [22:04:56 ERROR]: Unable to load plugin plugins\CatSeedLogin-1.4.1-SNAPSHOT.jar com.velocitypowered.api.plugin.InvalidPluginException: The plugin file CatSeedLogin-1.4.1-SNAPSHOT.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.         at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:161) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:62) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)] [22:04:56 ERROR]: Couldn't load plugins java.lang.IllegalArgumentException: Multiple entries with same key: skinsrestorer=VelocityPluginDescription{id='skinsrestorer', name='SkinsRestorer', version='15.0.2', description='Ability to restore/change skins on servers!', url='https://skinsrestorer.net', authors=[knat, AlexProgrammerDE, Blackfire62, McLive], dependencies={floodgate=PluginDependency{id='floodgate', version='null', optional=true}}, source=plugins\SkinsRestorer.jar} and skinsrestorer=VelocityPluginDescription{id='skinsrestorer', name='SkinsRestorer', version='15.0.4', description='Ability to restore/change skins on servers!', url='https://skinsrestorer.net', authors=[knat, AlexProgrammerDE, Blackfire62, McLive], dependencies={floodgate=PluginDependency{id='floodgate', version='null', optional=true}}, source=plugins\SkinsRestorer-14.2.12_648c7d9d26b62b00351c35a7.jar}. To index multiple values under a key, use Multimaps.index.         at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.google.common.collect.Maps.uniqueIndex(Maps.java:1340) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.plugin.util.PluginDependencyUtils.sortCandidates(PluginDependencyUtils.java:63) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:108) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]         at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)]        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.3.0-SNAPSHOT-389.jar:3.3.0-SNAPSHOT (git-1228f147-b389)] [22:04:56 INFO]: Loaded 0 plugins [22:04:56 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565 [22:04:56 INFO]: Done (1.9s)!

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### What client are you using?

PCL2

### SkinsRestorer Version

15.0.2

### List of plugins

CatSeedLogin-1.4.1-SNAPSHOT    hypermotd-velocity-1.0.1    SkinsRestorer

### Java Version

java version "21.0.2" 2024-01-16 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
@tonyxx1 Please translate your issue using a translator

**Comment by tonyxx1** [comment]
> 请使用翻译器翻译您的问题

I can't use SkinsRestorer on velocity

**Comment by tonyxx1** [comment]
Installing SkinsRestorer causes all plugins to become unusable (including SkinsRestorer). After installation, the plug-in that was successfully loaded became 0.

**Comment by tonyxx1** [comment]
> 请使用翻译器翻译您的问题

Installing SkinsRestorer causes all plugins to become unusable (including SkinsRestorer). After installation, the plug-in that was successfully loaded became 0.

**Comment by AlexProgrammerDE** [comment]
> [22:04:56 ERROR]: Unable to load plugin plugins\CatSeedLogin-1.4.1-SNAPSHOT.jar com.velocitypowered.api.plugin.InvalidPluginException: The plugin file CatSeedLogin-1.4.1-SNAPSHOT.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.

CatSeedLogin is the issue. Remove it and try again and send full logs.

**Comment by AlexProgrammerDE** [comment]
Closing due to inactivity
