### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by BZxmxs** [SkinsRestorer/SkinsRestorerX#1611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

That's right, plugin error：

[SkinsRestorer] Failed to save player skin data for 696452bc-c0d6-4979-86fb-bb3fbe24485f
java.nio.file.FileSystemException: plugins/SkinsRestorer/skins/696452bc-c0d6-4979-86fb-bb3fbe24485f.playerskin: Error writing extended attribute 'sr_last_known_name': Unsupported actions
	at sun.nio.fs.UnixUserDefinedFileAttributeView.write(UnixUserDefinedFileAttributeView.java:284) ~[?:?]
	at sun.nio.fs.UnixUserDefinedFileAttributeView.write(UnixUserDefinedFileAttributeView.java:265) ~[?:?]
	at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.setPlayerSkinData(FileAdapter.java:295) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.setPlayerSkinData(SkinStorageImpl.java:177) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.updatePlayerSkinData(SkinStorageImpl.java:115) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:164) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorageImpl.getPlayerSkin(SkinStorageImpl.java:125) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:136) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:108) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.handleAsync(LoginProfileListenerAdapter.java:69) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.lambda$handleLogin$0(LoginProfileListenerAdapter.java:50) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent$1.runAsync(PaperPlayerJoinEvent.java:80) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent$1.runAsync(PaperPlayerJoinEvent.java:52) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.handleLogin(LoginProfileListenerAdapter.java:48) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent.onAsyncPreLogin(PaperPlayerJoinEvent.java:48) ~[SkinsRestorer.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:395) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:280) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How can we reproduce what you got?

[20:01:45 警告]: [SkinsRestorer] Failed to get release info from api.github.com. 
 If this message is repeated a lot, please see https://skinsrestorer.net/firewall
[20:02:48 信息]: [GroupManager] Async Player Login event refresh data... 
[20:02:48 信息]: [GroupManager] Async Player Login event finshed. 

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### What client are you using?

pcl2

### SkinsRestorer Version

15.0.13

### List of plugins

[20:40:59 信息]: Server Plugins (53): [20:40:59 信息]: Bukkit Plugins: [20:40:59 信息]:  - BlockLocker, Boom, CatSeedLogin, Chunky, CMILib, ColorfulMap, ConsoleSpamFix, CooPay, CoreProtect, CustomVillagerSkins [20:40:59 信息]:  DeEnchantment, FastMinecartsPlus, floodgate, Geyser-Spigot, GeyserUpdater, GiftPack, GlobalMarketChest, GlobalMarketPlus, GroupManager, GSit [20:40:59 信息]:  *KillerMoney, LibsDisguises, LuckBedrock, LuckPerms, MagicAvatar, MCEEW, *McPing, MiniMOTD, MoneyFromMobs, NBTAPI [20:40:59 信息]:  Pcc_limbo_system, PlaceholderAPI, PlayerMenu, PlayerPoints, PlayerTitle, ProtocolLib, Residence, *SeekInventory, *SetHome, SimpleTpa [20:40:59 信息]:  SkinsRestorer, Spectator, TAB, TimeMissingPlugin, UniversalProtocol, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit [20:40:59 信息]:  XConomy, YukiNoaAPI, ZMusic

### Java Version

17

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Should be fixed in 15.3.1.
