### ISSUE TITLE
Error on Task 4 and 6

### ISSUE THREAD

**Issue by FastzinDasBurlas** [SkinsRestorer/SkinsRestorerX#1640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

the server starts normally, but the plugin gives an error

Log of my server

## 

***********************************************************
[10:22:30 WARN]: * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
[10:22:30 WARN]: * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
[10:22:30 WARN]: * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
[10:22:30 WARN]: *
[10:22:30 WARN]: * Please update the version of Java you use to run Paper
[10:22:30 WARN]: * to at least Java 16. When Paper for Minecraft 1.17 is
[10:22:30 WARN]: * released support for versions of Java before 16 will
[10:22:30 WARN]: * be dropped.
[10:22:30 WARN]: *
[10:22:30 WARN]: * Current Java version: 1.8.0_411
[10:22:30 WARN]: *
[10:22:30 WARN]: * Check this forum post for more information: 
[10:22:30 WARN]: *   https://papermc.io/java16
[10:22:30 WARN]: ************************************************************
[10:22:30 INFO]: Timings Reset
[10:22:31 WARN]: Plugin SkinsRestorer v15.0.14 generated an exception while executing task 4
java.lang.NoSuchMethodError: java.io.ByteArrayOutputStream.toString(Ljava/nio/charset/Charset;)Ljava/lang/String;
	at net.skinsrestorer.shared.connections.http.HttpClient.execute(HttpClient.java:107) ~[?:?]
	at net.skinsrestorer.shared.update.UpdateCheckerGitHub.checkForUpdate(UpdateCheckerGitHub.java:65) ~[?:?]
	at net.skinsrestorer.shared.update.UpdateCheckExecutor.lambda$checkUpdate$0(UpdateCheckExecutor.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_411]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]
[10:22:32 WARN]: Plugin SkinsRestorer v15.0.14 generated an exception while executing task 6
java.lang.NoSuchMethodError: java.io.ByteArrayOutputStream.toString(Ljava/nio/charset/Charset;)Ljava/lang/String;
	at net.skinsrestorer.shared.connections.http.HttpClient.execute(HttpClient.java:107) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:239) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.readURL(MojangAPIImpl.java:232) ~[?:?]
	at net.skinsrestorer.shared.connections.MojangAPIImpl.getUUIDEclipse(MojangAPIImpl.java:114) ~[?:?]
	at net.skinsrestorer.shared.connections.ServiceCheckerService.checkServices(ServiceCheckerService.java:54) ~[?:?]
	at net.skinsrestorer.shared.plugin.SRPlugin.runServiceCheck(SRPlugin.java:440) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_411]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_411]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_411]

### Minecraft implementation

```markdown
- Proxy:
- Backend:
```

### SkinsRestorer Version

15.0.14

### List of plugins

Only Skins Restorer

### Java Version

1.8.0_411

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
Can you try java 17?

**Comment by FastzinDasBurlas** [comment]
already tried, the paper mc server dont open, only with the java 8 it opens

**Comment by AlexProgrammerDE** [comment]
Fixed with 15.0.15
