### ISSUE TITLE
Stacktrace on player skin set

### ISSUE THREAD

**Issue by SaintPepsix** [SkinsRestorer/SkinsRestorerX#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Been getting this Stacktrace on 1.20.4 for all compatible versions (including latest) :

[SkinsRestorer] Failed to set skin data of player 699bc69f-42c3-3000-81e5-c4271ced7c69
net.skinsrestorer.shared.storage.adapter.StorageAdapter$StorageException: net.skinsrestorer.shadow.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:238) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.storage.PlayerStorageImpl.setSkinIdOfPlayer(PlayerStorageImpl.java:67) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:282) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:202) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:185) ~[SkinsRestorer.jar:?]
at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
at net.skinsrestorer.shared.commands.library.BrigadierCommand.lambda$run$0(BrigadierCommand.java:70) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer.jar:?]
at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[paper-1.20.4.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.skinsrestorer.shadow.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at net.skinsrestorer.shadow.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1227) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1137) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1047) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:982) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:234) ~[SkinsRestorer.jar:?]
... 11 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at net.skinsrestorer.shadow.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1227) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1137) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:1047) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shadow.google.gson.Gson.fromJson(Gson.java:982) ~[SkinsRestorer.jar:?]
at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:234) ~[SkinsRestorer.jar:?]
... 11 more

Followed by a successful skin change when using the "skin set test PlayerName" command where test is a skin stored locally as a valid .customskin file in the skins folder

Here is the content of the test.customskin file :

{"skinName":"test","value":"ewogICJ0aW1lc3RhbXAiIDogMTYzMjA5Njg1MzI5NywKICAicHJvZmlsZUlkIiA6ICJmNWQwYjFhZTQxNmU0YTE5ODEyMTRmZGQzMWU3MzA1YiIsCiAgInByb2ZpbGVOYW1lIiA6ICJDYXRjaFRoZVdhdmUxMCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZTA1OWMwNjkxYzc2ZTQzYmQ5OWFhN2NkYzg4NTM4ZGEzMmJkYzM3NzY5MzI5NzlhMWMwNGJiZmM2YzNlNGU0IgogICAgfQogIH0KfQ==","signature":"XcuIrnMzGAJ+uY6taYxyANFZKMpinTTF/CmcDtduhyxZKK2ZydHgROI3FvzRf4Z0KUqovUiprMTP0PMzWXpWD131JBxo696JiRf1iXc/gS/3og5JCnvhTZMDRp3XQl3kAPRbi/BXo4d9k4DuDYpzQIZ809Y54/c68IS+7P6ixTyOqDRZyUCgYtwe+yzYTihRLGXVw6BXdMeRozP1d6IYa780gqStXxHIEtiKwPjplcF6okK3dxuh0gwKY2UjcS6zRmXnZLKtvWW+xyDGRm4QxZQ+B0pXY88xEwJhFt7EHiY0ucRzOYr9rEzU60IyFYUd5dfiNpEWAKAYW38ijOqV4COymKMGRZgW0DsiFRB/GIjVmm5U+ldSnxt+5xi7tWgyEEPcolyGY4T46TfX+3aIMEWnOX4Y5i+AGAtDspUhojXY61Qd9z8huzcIw0UAFUw4jhpgzwKMpCVCnKXA8Ly+PFWqqLjnx1G3ueWJVuSeUvH7qCqEMBuu7ZF9pQ18YilDZsWR0bYZaBzvgl4l6FNNRSuach/WhuZDUSPw1Xu4Jo2RugBl7zvdVlPeWZ0ulG7fc5Qi2yTidmrZhNE/ZgYAJKwz7UBR+LW8qH3k6U1mbqn8mgBAJWYH0elChZHcXweCcUiIW3lWE349wr7Z4WGp+yf7I/NONZzADjUeCrUg9vo=","dataVersion":1}

### How can we reproduce what you got?

1. Install SkinsRestorer normally and add test.customskin to skins folder
2. Run the "skin set test PlayerName" command
3. Stacktrace appears in console but skin is correctly set

### Minecraft implementation

```markdown
"This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)"
```

### What client are you using?

Vanilla Launcher

### SkinsRestorer Version

15.0.15

### List of plugins

Server Plugins (25): Paper Plugins: - BKCommonLib : Bukkit Plugins: - BetterPortals, Citizens, ConsoleSpamFix, DecentHolograms, Essentials, *eZLink, FastAsyncWorldEdit, GadgetsMenu, JSONAPI-RELOADED-UNIVERSAL, LibsDisguises, LightCleaner, ModelEngine, Multiverse-Core, MythicMobs, *PermissionsEx, PlaceholderAPI, PortableCraftingInvs, ProtocolLib, SkinsRestorer, TitleAPI, Vault, WorldGuard, WorldGuardExtraFlags

### Java Version

"17.0.5" 2022-10-18 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by xknat** [comment]
@SaintPepsix should be resolved in latest dev build please test

**Comment by SaintPepsix** [comment]
Seems to still be happening on :

![image](https://github.com/user-attachments/assets/ed2ddace-0d5d-4aec-b871-8e7c79e15afd)


`[10:39:20 ERROR]: [SkinsRestorer] Failed to get skin data of player 699bc69f-42c3-3000-81e5-c4271ced7c69
net.skinsrestorer.shared.storage.adapter.StorageAdapter$StorageException: net.skinsrestorer.shadow.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:223) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinIdOfPlayer(PlayerStorageImpl.java:56) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:277) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:273) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.handleAsync(LoginProfileListenerAdapter.java:68) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.lambda$handleLogin$0(LoginProfileListenerAdapter.java:50) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent$1.runAsync(PaperPlayerJoinEvent.java:80) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent$1.runAsync(PaperPlayerJoinEvent.java:52) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.listeners.LoginProfileListenerAdapter.handleLogin(LoginProfileListenerAdapter.java:48) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.paper.PaperPlayerJoinEvent.onAsyncPreLogin(PaperPlayerJoinEvent.java:48) ~[SkinsRestorer.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.callPlayerPreLoginEvents(ServerLoginPacketListenerImpl.java:320) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:172) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: net.skinsrestorer.shadow.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1361) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1262) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1171) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1107) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:219) ~[SkinsRestorer.jar:?]
        ... 21 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shadow.gson.stream.JsonReader.unexpectedTokenError(JsonReader.java:1768) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.stream.JsonReader.beginObject(JsonReader.java:469) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1361) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1262) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1171) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1107) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:219) ~[SkinsRestorer.jar:?]
        ... 21 more
[10:39:21 ERROR]: [SkinsRestorer] Failed to set skin data of player 699bc69f-42c3-3000-81e5-c4271ced7c69
net.skinsrestorer.shared.storage.adapter.StorageAdapter$StorageException: net.skinsrestorer.shadow.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:223) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.setSkinIdOfPlayer(PlayerStorageImpl.java:72) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.setSkin(SkinCommand.java:522) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:299) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.commands.SkinCommand.onSkinSetOther(SkinCommand.java:287) ~[SkinsRestorer.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[?:?]
        at net.skinsrestorer.shadow.cloud.annotations.MethodCommandExecutionHandler.executeFuture(MethodCommandExecutionHandler.java:88) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.cloud.execution.ExecutionCoordinatorImpl.lambda$coordinateExecution$4(ExecutionCoordinatorImpl.java:121) ~[SkinsRestorer.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?]
Caused by: net.skinsrestorer.shadow.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1361) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1262) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1171) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1107) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:219) ~[SkinsRestorer.jar:?]
        ... 15 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
        at net.skinsrestorer.shadow.gson.stream.JsonReader.unexpectedTokenError(JsonReader.java:1768) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.stream.JsonReader.beginObject(JsonReader.java:469) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1361) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1262) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1171) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shadow.gson.Gson.fromJson(Gson.java:1107) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.adapter.file.FileAdapter.getPlayerData(FileAdapter.java:219) ~[SkinsRestorer.jar:?]
        ... 15 more`

**Comment by xknat** [comment]
@SaintPepsix should be fixed now. please join our discord support if not resolved
