### ISSUE TITLE
java.lang.stringindexoutofboundsexception

### ISSUE THREAD

**Issue by GG-MD** [SkinsRestorer/SkinsRestorerX#1794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Error message in console
```
[13:55:47] [Netty Worker IO Thread #7/WARN]: Error in
dispatching command java.lang.RuntimeException:
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for
length 0
������� at net.skinsrestorer.shadow.cloud.annotations.suggestion.MethodSuggestionProvi>
������� at net.skinsrestorer.shadow.cloud.CommandTree.addArgumentSuggestions(CommandTr>
������� at net.skinsrestorer.shadow.cloud.CommandTree.addArgumentSuggestions(CommandTr>
������� at net.skinsrestorer.shadow.cloud.CommandTree.addSuggestionsForDynamicArgument>
������� at net.skinsrestorer.shadow.cloud.CommandTree.lambda$getSuggestions$18(Command>
������� at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.ja>
������� at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2>
������� at net.skinsrestorer.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:>
������� at net.skinsrestorer.shadow.cloud.CommandTree.getSuggestions(CommandTree.java:>
������� at net.skinsrestorer.shadow.cloud.CommandTree.getSuggestionsDirect(CommandTree>
������� at net.skinsrestorer.shadow.cloud.CommandTree.lambda$getSuggestions$13(Command>
������� at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.ja>
������� at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.j>
������� at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
������� at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:>
������� at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
������� at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
������� at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188>
Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for >
������� at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
������� at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
������� at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
������� at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
������� at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
������� at jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.j>
������� at jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[>
������� at java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
������� at java.lang.String.substring(String.java:2834) ~[?:?]
������� at net.skinsrestorer.shared.commands.SRCommand.suggestSkinInputUrl(SRCommand.j>
������� at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733) ~[>
������� at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758) ~[>
������� at net.skinsrestorer.shadow.cloud.annotations.suggestion.MethodSuggestionProvi>
������� ... 17 more
```

### Minecraft implementation

```markdown
- Proxy: nullcordx dev build
- Backend: Purpur 1.21.1 latest
```

### SkinsRestorer Version

Latest

### List of plugins

-

### Java Version

21

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Should be fixed by https://github.com/SkinsRestorer/SkinsRestorer/commit/dac13d6a8a407fb996b302a571b84d75c795fedd
