### ISSUE TITLE
1.21.1 GameProfile error

### ISSUE THREAD

**Issue by GG-MD** [SkinsRestorer/SkinsRestorerX#1814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

```
[12:20:41 INFO]: [Not Secure] Ⓛ ᴘʀᴇᴍɪᴜᴍ PzKpfw_VI_T1ger ᴡᴀʀʀɪᴏʀ: добыть кварц?
[12:20:44 WARN]: [SkinsRestorer] Async task for SkinsRestorer v15.4.3 generated an exception
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.gui.BukkitGUI.lambda$createItem$0(BukkitGUI.java:72) ~[SkinsRestorer.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.gui.BukkitGUI.createItem(BukkitGUI.java:58) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.gui.BukkitGUI.createGUI(BukkitGUI.java:101) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.SRBukkitAdapter.openGUI(SRBukkitAdapter.java:163) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.shared.listeners.SRServerMessageAdapter.lambda$handlePluginMessage$0(SRServerMessageAdapter.java:44) ~[SkinsRestorer.jar:?]
        at SkinsRestorer.jar/net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:20:45 INFO]: PzKpfw_VI_T1ger issued server command: /rtp
>
```

### How can we reproduce what you got?

Unknown, just an occasional error on the sub servers. NullCordX (proxy), PurPur 1.21.1 latest release build. 

### SkinsRestorer Version

15.4.3

### List of plugins

[12:24:21 INFO]:  - FancyNpcs, MarriageMaster [12:24:21 INFO]: Bukkit Plugins: (59): [12:24:21 INFO]:  - AdvancedEnchantments, ajLeaderboards, antiRedstoneClock, BAirDrop, BattlePass, BookNews, BungeeGuard, Chatty, ChestSort, Chunky [12:24:21 INFO]:  ChunkyBorder, CMI, CMILib, CoreProtect, DecentHolograms, DeluxeCombat, DeluxeMenus, Duels, EasyPayments, FacilisCommon [12:24:21 INFO]:  FastAsyncWorldEdit, GadgetsMenu, GGitems, GGMblockADs, GGMcmdCooldown, GGMcore, GGMevents, GGMitemJoin, GGMmobai, GGMpoints [12:24:21 INFO]:  GGMshops, GGMsub, GraceCases, Granter, IBAirAddon, LiteBans, LuckPerms, MobFarmManager, MultiWorld, PetNameFix [12:24:21 INFO]:  PlaceholderAPI, PlayerPoints, PlayerWarps, PlugManX, ProtocolLib, SkinsRestorer, TAB, TabCompleteFilter, TigerReports, TradeSystem [12:24:21 INFO]:  UltimateClans, Vault, ViaBackwards, ViaVersion, Vulcan, WGExtender, WorldEditSelectionVisualizer, WorldGuard, zAuctionHouseV3

### Java Version

21 latest 

### Does your issue require a plugin in order to reproduce?

None

**Comment by GG-MD** [comment]
Maybe because Mojang changed the skull GameProfile in skull builds not so long ago ? 🤷🏽‍♂️

**Comment by GG-MD** [comment]
_It also doesn't open the GUI with skins, where those very heads are located :)_

**Comment by xknat** [comment]
Can you try our dev build? https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/

**Comment by GG-MD** [comment]
> Can you try our dev build? https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/

Yes, I’ll give it a try, thank you.

**Comment by GG-MD** [comment]
> Can you try our dev build? https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/

Yes, everything works perfectly now. 👍🏽👍🏽👍🏽

**Comment by daretmavi** [comment]
Same issue with paper-1.21.1-128. Latest Snapshot works.

**Comment by GG-MD** [comment]
> Same issue with paper-1.21.1-128. Latest Snapshot works.

The response above was provided – the issue has been resolved.
