### ISSUE TITLE
The skins menu cannot be used in the Velocity sub-server.

### ISSUE THREAD

**Issue by Noogear** [SkinsRestorer/SkinsRestorerX#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

The skins menu cannot be used in the Velocity sub-server. And in the sub-server, the plugin with soft dependency on SR will report an error.

### How can we reproduce what you got?

nstall the SR plugin correctly in Velocity and the sub-server.
Then when using the plugin with soft dependency on SR and the command /skins, an error will be reported.
When I use /skins, there will be the following prompt.
```
[18:27:10 WARN]: [SkinsRestorer] Async task for SkinsRestorer v15.4.3 generated an exception
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.bukkit.gui.BukkitGUI.lambda$createItem$0(BukkitGUI.java:72) ~[SkinsRestorer (5).jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.bukkit.gui.BukkitGUI.createItem(BukkitGUI.java:58) ~[SkinsRestorer (5).jar:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.bukkit.gui.BukkitGUI.createGUI(BukkitGUI.java:101) ~[SkinsRestorer (5).jar:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.bukkit.SRBukkitAdapter.openGUI(SRBukkitAdapter.java:163) ~[SkinsRestorer (5).jar:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.shared.listeners.SRServerMessageAdapter.lambda$handlePluginMessage$0(SRServerMessageAdapter.java:44) ~[SkinsRestorer (5).jar:?]
        at SkinsRestorer (5).jar/net.skinsrestorer.bukkit.folia.FoliaSchedulerProvider.lambda$getCancellingTaskConsumer$0(FoliaSchedulerProvider.java:84) ~[SkinsRestorer (5).jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[leaf-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Server/Error Logs

https://bin.birdflop.com/cahupeguki.makefile

### Minecraft implementation

```markdown
This server is running Leaf version 1.21.1-DEV-ver/1.21.1@6ffcb57 (2024-10-02T17:52:29Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are 5 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous: 1.21.1-DEV-4548da8 (MC: 1.21.1)

velocity 3.3.0 (git-2016d148-b436)
```

### SkinsRestorer Version

14.2.4 And I also tried the latest build version, and this problem also exists.

### List of plugins

[17:11:15 INFO]:  - Aiyatsbus, ArmorStandEditor, AuraMobs, AuraSkills, AuthMe, BentoBox, BentoBox-AOneBlock, BentoBox-Biomes, BentoBox-Challenges, BentoBox-Level [17:11:15 INFO]:  BentoBox-TopBlock, BentoBox-Warps, ChunkHopper, CoinsEngine, ColorfulMap, Craftorithm, DamageDisplay, DecentHolograms, ExcellentShop, ItemEdit [17:11:15 INFO]:  LuckPerms, MythicPrefixes, nightcore, Oraxen, PlaceholderAPI, protectall, ProtocolLib, QuickSave, SkinsRestorer, SunLight [17:11:15 INFO]:  TileDataSaver, TrMenu, UTitleAuth, Vault, WanderingTrades, WorldEdit

### Java Version

java version "22.0.2" 2024-07-16 Java(TM) SE Runtime Environment Oracle GraalVM 22.0.2+9.1 (build 22.0.2+9-jvmci-b01) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment]
Fixed in 15.4.4
