### ISSUE TITLE
"recommenationResponse" is null

### ISSUE THREAD

**Issue by jfoucher** [SkinsRestorer/SkinsRestorerX#1852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Error message in console : 

[15:40:34 INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.4.4
[15:40:35 WARN]:  [ 2mSkinsRestorer ]   You must agree to the rules at 'commands.perSkinPermissionsConsent' in the config to use per skin permissions. 
[15:40:35 INFO]:  [ 2mSkinsRestorer ]   Running on Minecraft  1.20.4 . 
[15:40:35 INFO]:  [ 2mSkinsRestorer ]  Using paper join listener! 
[15:40:35 INFO]: [PlaceholderAPI] Successfully registered internal expansion: skinsrestorer [15.4.4]
[15:40:35 INFO]:  [ 2mSkinsRestorer ]  PlaceholderAPI expansion registered! 
[15:40:35 ERROR]: An unexpected error occurred while starting the plugin. Please check the console for more details.
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.shared.connections.responses.RecommenationResponse.getSkins()" because "recommenationResponse" is null
	at net.skinsrestorer.shared.connections.RecommendationsState.scheduleRecommendations(RecommendationsState.java:69) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.plugin.SRPlugin.startup(SRPlugin.java:345) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.plugin.SRBootstrapper.startPlugin(SRBootstrapper.java:62) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SRBukkitBootstrap.onEnable(SRBukkitBootstrap.java:45) ~[SkinsRestorer.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-446]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-446]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-446]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Minecraft implementation

```markdown
- Proxy:none
- Backend:paper-1.20.4-446.jar or paper-1.20.4-497.jar
```

### SkinsRestorer Version

v15.4.4

### List of plugins

[15:49:00 INFO]:  Server Plugins (69):  [15:49:00 INFO]:  Bukkit Plugins:  [15:49:00 INFO]:   -   AntiAC ,  ArenaSpleef ,  AuctionHouse ,  BackpackPlus ,  BattleArena ,  BedWars ,  BetterRTP ,  builder ,  ChatGames ,  Chunky  [15:49:00 INFO]:   Citizens ,  CityWorld ,  CMILib ,  Essentials ,  EssentialsAntiBuild ,  EssentialsChat ,  ExcellentCrates ,  FancyHolograms ,  FighterCommand ,  FreeClaims  [15:49:00 INFO]:   GPS ,  GrimAC ,  GSit ,  HeadDrop ,  HungerGames ,  ItemGiver ,  Jobs ,  Katana ,  LoginNotification ,  LoginSecurity  [15:49:00 INFO]:   Lottery ,  LuckPerms ,  MagicHoe ,  MagicTeleport ,  arteau ,  axihache ,  MechanicsCore ,  ielsucre ,  Multiverse-Core ,  Multiverse-Inventories  [15:49:00 INFO]:   Multiverse-NetherPortals ,  Multiverse-Portals ,  NexEngine ,  ODailyQuests ,  Offrande ,  Oneblock ,  PeriodicMessage ,  PermissionRemover ,  PlaceholderAPI ,  PlayerFidelity  [15:49:00 INFO]:   pouleTueuse ,  ProtocolLib ,  Sentinel ,  SkinsRestorer ,  SpawnerPickaxe ,  SternalBoard ,  SuperiorSkyblock2 ,  TapeMeasure ,  TempFly ,  TradeSystem  [15:49:00 INFO]:   uShop ,  Vault ,  * VoidGenerator ,  WeaponMechanics ,  WildStacker ,  WordReplacer ,  WorldEdit ,  WorldGuard ,  * xAntiAFK 

### Java Version

openjdk version "17.0.9" 2023-10-17

### Does your issue require a plugin in order to reproduce?

No

**Comment by AlexProgrammerDE** [comment]
Fixed by e210b019ae4d864e187f7c2825b0ef6aa610f42d
