### ISSUE TITLE
IllegalStateException on skinurl /skin update

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#202]
A error is thrown when the JSON object is null, there should be a new warning informing the player that a skinurl can not be updated so that server owners are not mis informed about errors. 
```
15:11:12 [INFO] [SkinsRestorer] Sending skin update request for ....
15:11:13 [SEVERE] java.lang.IllegalStateException: Not a JSON Object: null
15:11:13 [SEVERE] at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
15:11:13 [SEVERE] at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:77)
15:11:13 [SEVERE] at skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:50)
15:11:13 [SEVERE] at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:198)
15:11:13 [SEVERE] at skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:140)
15:11:13 [SEVERE] at skinsrestorer.bungee.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:130)
15:11:13 [SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
15:11:13 [SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:11:13 [SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:11:13 [SEVERE] at java.lang.Thread.run(Thread.java:748)
```

**Comment by xknat** [comment]
Should be resolved with #217 and #215
