### ISSUE TITLE
null || Null Skin Problem !

### ISSUE THREAD

**Issue by hidirektor** [SkinsRestorer/SkinsRestorerX#204]
I get the following error when im trying to use null or Null skins.

`[00:30:30 INFO]: SYN_T3SL4 issued server command: /skin null
[00:30:30 WARN]: java.lang.NullPointerException
[00:30:30 WARN]:        at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:163)
[00:30:30 WARN]:        at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:369)
[00:30:30 WARN]:        at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:405)
[00:30:30 WARN]:        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:134)
[00:30:30 WARN]:        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:148)
[00:30:30 WARN]:        at skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:174)
[00:30:30 WARN]:        at skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:142)
[00:30:30 WARN]:        at skinsrestorer.bukkit.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:134)
[00:30:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:30:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:30:30 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[00:30:30 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:30:30 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:30:30 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by aljaxus** [comment]
rofl - "command injection" in Spigot plugins 😂 

Are you using the very latest version of SR (13.7.5) ?
Also, why have you created two issues ( #203 ) for quite literally the same problem?
![image](https://user-images.githubusercontent.com/24414483/74927770-89e8d400-53d8-11ea-9b71-63186c0ad974.png)
The only difference is that #204 is triggered via command execution and #203 is triggered via join event. Please close issue #203 

Also, please provide all of the following information;
SkinsRestorer version (exact version that you get in the console when the server starts up)
Server version (spigot / paper / bungee and version string)
Database type

Kind regards

**Comment by hidirektor** [comment]
> rofl - "command injection" in Spigot plugins 😂
> 
> Are you using the very latest version of SR (13.7.5) ?
> Also, why have you created two issues ( #203 ) for quite literally the same problem?
> ![image](https://user-images.githubusercontent.com/24414483/74927770-89e8d400-53d8-11ea-9b71-63186c0ad974.png)
> The only difference is that #204 is triggered via command execution and #203 is triggered via join event. Please close issue #203
> 
> Also, please provide all of the following information;
> SkinsRestorer version (exact version that you get in the console when the server starts up)
> Server version (spigot / paper / bungee and version string)
> Database type
> 
> Kind regards

SkinsRestorer version: 13.7.5 & 13.7.6-SNAPSHOT
Server version: PaperSpigot-1.8.8-R0.1-SNAPSHOT
Database type: Flat File
Console Errors or warns: ----

**Comment by xknat** [comment]
We are looking on blocking the null || Null skin.
