### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by dani17val** [SkinsRestorer/SkinsRestorerX#206]
When I run my plugin it says that there was a ClassCastException at the line 28 (skinsRestorer inicialization at onEnable)
My onEnable:
```
@Override
    public void onEnable() {
        Bukkit.getServer().getPluginManager().registerEvents(this, this);
        if(Bukkit.getWorld("auth") != null){
            auth = Bukkit.createWorld(new WorldCreator("auth").generator(new GenerarVoid()));
        }
        skinsRestorer = JavaPlugin.getPlugin(SkinsRestorer.class);
        skinsRestorerBukkitAPI = skinsRestorer.getSkinsRestorerBukkitAPI();

    }
```
Error:
`[14:44:03] [Server thread/ERROR]: Error occurred while enabling Mineuniverso v1.0-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: Cannot cast com.danimania.mineuniverso.Mineuniverso to skinsrestorer.bukkit.SkinsRestorer
        at java.lang.Class.cast(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:397) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at com.danimania.mineuniverso.Mineuniverso.onEnable(Mineuniverso.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by xknat** [comment]
You need to use the api...
and not directly call classes.
