### ISSUE TITLE
I have some ERROR on

### ISSUE THREAD

**Issue by mitokohaku** [SkinsRestorer/SkinsRestorerX#238]
21:53:10 [INFO] [Lao_da_gou,/**********:10180] <-> InitialHandler has connected

Bungee's ERROR:
21:53:12 [SEVERE] java.lang.NullPointerException
21:53:12 [SEVERE]     at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:163)
21:53:12 [SEVERE]     at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:369)
21:53:12 [SEVERE]     at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:405)
21:53:12 [SEVERE]     at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:134)
21:53:12 [SEVERE]     at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:148)
21:53:12 [SEVERE]     at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:33)
21:53:12 [SEVERE]     at skinsrestorer.bungee.listeners.LoginListener.lambda$onServerChange$0(LoginListener.java:49)
21:53:12 [SEVERE]     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21:53:12 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:53:12 [SEVERE]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:53:12 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
21:53:12 [INFO] [Lao_da_gou] <-> ServerConnector [main] has connected
21:53:12 [INFO] [Lao_da_gou] disconnected with: Kicked whilst connecting to main: Failed to verify username!

Spigot ERROR:
[21:57:38 INFO]: Disconnecting com.mojang.authlib.GameProfile@311cbbcd[id=b8634b4b-cc7c-3722-b677-5b2c50b55df2,name=Lao_da_gou,properties={},legacy=false] (/**********:60995): Failed to verify username!
[21:57:38 WARN]: Exception verifying Lao_da_gou java.lang.NullPointerException: null
        at net.minecraft.server.v1_15_R1.LoginListener.initUUID(LoginListener.java:138) ~[patched_1.15.2.jar:git-Paper-102]
        at net.minecraft.server.v1_15_R1.LoginListener$1.run(LoginListener.java:211) ~[patched_1.15.2.jar:git-Paper-102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[21:57:38 INFO]: com.mojang.authlib.GameProfile@311cbbcd[id=b8634b4b-cc7c-3722-b677-5b2c50b55df2,name=Lao_da_gou,properties={},legacy=false] (/**********:60995) lost connection: Failed to verify username!

Some player can not login the server because the plugin 
I have no idea about that

**Comment by xknat** [comment]
@mitokohaku has been fixed on 9588ba2fd6c581c3edf663d527d28d420d7c56c2
