### ISSUE TITLE
/skins doesn't work and creates an exception

### ISSUE THREAD

**Issue by AMDBartek** [SkinsRestorer/SkinsRestorerX#293]
## Describe the bug
When a player runs the /skins command it will say `Opening the skins menu...` in chat and the menu never shows.

## How can we reproduce what you got?
1. Execute /skins
2. Go to the server console
3. Scroll down to '[SkinsRestorer] Plugin SkinsRestorer v13.8.2 generated an exception while executing task XXX'

**I have attached the exception from my server as well:**
```
[19:56:06 WARN]: [SkinsRestorer] Plugin SkinsRestorer v13.8.2 generated an exception while executing task 640
java.lang.NullPointerException: null
        at skinsrestorer.bukkit.SkinsGUI.createSkull(SkinsGUI.java:155) ~[?:?]
        at skinsrestorer.bukkit.SkinsGUI.lambda$getGUI$0(SkinsGUI.java:127) ~[?:?]
        at java.util.TreeMap.forEach(TreeMap.java:1005) ~[?:1.8.0_251]
        at skinsrestorer.bukkit.SkinsGUI.getGUI(SkinsGUI.java:119) ~[?:?]
        at skinsrestorer.bukkit.SkinsGUI.getGUI(SkinsGUI.java:144) ~[?:?]
        at skinsrestorer.bukkit.commands.GUICommand.lambda$onDefault$1(GUICommand.java:40) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

**Expected behavior**
The /skins menu to work (not much to say really).

**Screenshots**
N/A, screenshots wouldn't contain useful information.

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: 13.8.2
* Spigot version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
* Bungeecord version: Not running bungeecord
* IF bungee, did you put the plugin on all servers: Not bungee
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com/AMDBartek/5f1acff7d4fe71da1bd4f81cd63e86ef

## Additional context
N/A

**Comment by xknat** [comment]
Please zip and upload your skins from bungee

**Comment by xknat** [comment]
Edit: i mean spigot ./plugin/skinsrestorer/skins/

**Comment by AMDBartek** [comment]
Ok, will do, most ae custom skins. is 7z ok?

**Comment by AMDBartek** [comment]
I managed to fix it, It was a corrupted skin.
