### ISSUE TITLE
Can't load the plugin on paper-148(MC 1.16.2)

### ISSUE THREAD

**Issue by winup-zhou** [SkinsRestorer/SkinsRestorerX#304]
I download the plugin from spigotmc, The version of the plugin is 13.8.3

I installed it in the plugins folder
But when I sharted the server, the console showed me an error
`[19:03:51 ERROR]: Could not load 'plugins\SkinsRestorer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.2.jar:git-Paper-148]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.2.jar:git-Paper-148]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-148]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-148]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-148]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_261]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_261]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_261]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_261]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.2.jar:git-Paper-148]
        ... 6 more`

Server started successfully, but the plugin is not loaded...
`> plugins
[19:13:15 INFO]: Plugins (5): ColorMOTD*, Geyser-Spigot, LaggRemover, ProtocolLib, SpigotPing`

I loaded with the latest version ProtocolLib 4.5.1
（Sorry for my poor English,I am from China and using Google Translate）

here are the log
[latest.log](https://github.com/SkinsRestorer/SkinsRestorerX/files/5136047/latest.log)

**Comment by xknat** [comment]
java.util.zip.ZipFile.open
it could not open the zip, download again from https://github.com/SkinsRestorer/SkinsRestorerX/releases/latest/download/SkinsRestorer.jar
if you need user support, please join our discord

**Comment by winup-zhou** [comment]
I re-downloaded it three times, but the plugin still fails to load...maybe I should use Spigot？

**Comment by xknat** [comment]
![image](https://user-images.githubusercontent.com/10220139/91438644-fc48de00-e86b-11ea-951d-61134a8be235.png)

**Comment by xknat** [comment]
@winup-zhou if you cant install discord. contact us on spigotmc: https://www.spigotmc.org/conversations/add?to=SRTeam
