### ISSUE TITLE
Error while enabling plugin, "null"

### ISSUE THREAD

**Issue by developer-jx** [SkinsRestorer/SkinsRestorerX#307]
Spigot wouldn't load the plugin due to an error while enabling.
Using Minecraft Spigot 1.16.2

```
[02:08:25] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v13.8.3
[02:08:25] [Server thread/INFO]: [SkinsRestorer] Using PaperSkinRefresher
[02:08:25] [Server thread/INFO]: [SkinsRestorer] Detected Minecraft v1_16_R2, using UniversalSkinFactory.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] SkinWithoutPerm is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] SkinChangeCooldown is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] SkinErrorCooldown is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] DefaultSkins.Enabled is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] DefaultSkins.ApplyForPremium is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] DisabledSkins.Enabled is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] CustomGUI.Enabled is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] CustomGUI.ShowOnlyCustomGUI is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] DisablePrefix is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] UseOldSkinHelp is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] PerSkinPermissions is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] SkinExpiresAfter is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MultiBungee.Enabled is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Enabled is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Host is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Port is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Database is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Username is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.Password is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.SkinTable is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] MySQL.PlayerTable is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] DisableOnJoinSkins is missing in config.yml! Using default value.
[02:08:25] [Server thread/INFO]: [SkinsRestorer] NoSkinIfLoginCanceled is missing in config.yml! Using default value.
[02:08:25] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v13.8.3 (Is it up to date?)
java.lang.NullPointerException: null
        at skinsrestorer.shared.utils.YamlConfig.getString(YamlConfig.java:135) ~[?:?]
        at skinsrestorer.shared.utils.YamlConfig.getBoolean(YamlConfig.java:114) ~[?:?]
        at skinsrestorer.shared.storage.Config.load(Config.java:78) ~[?:?]
        at skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:199) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-141]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-141]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-141]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-141]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-141]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-141]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-141]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-141]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[02:08:25] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v13.8.3
```

**Comment by xknat** [comment]
skinsrestorer.shared.storage.Config.load
Think malformed config.
Also, github is not for user support. Please join discord
