### ISSUE TITLE
[H] Reduce Mysql Duplicate entry by using single insert OR update mysql command.

### ISSUE THREAD

**Issue by DenisJ9798** [SkinsRestorer/SkinsRestorerX#343]
https://stackoverflow.com/a/4205207
Use INSERT ... ON DUPLICATE KEY UPDATE

QUERY:

`INSERT INTO table (id, name, age) VALUES(1, "A", 19) ON DUPLICATE KEY UPDATE    
name="A", age=19`

### OC content
~~~~
Bungeecord

* SkinsRestorer: 13.8.4
* Spigot version:  1.16.4
* Bungeecord version:  last
* IF bungee, did you put the plugin on all servers: No
* Java: 8
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs
https://pastebin.com/CZkDPBFF

**Comment by xknat** [comment]
@DenisJ9798 can you check in mysql if there are 2 '_crack' inside name in skins table and name in players table
if you dont know how to please let me know

```
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '_crack' for key 'PRIMARY'
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.shared.utils.MySQL.execute(MySQL.java:148)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:381)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:407)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:131)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:145)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:34)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at skinsrestorer.bungee.listeners.LoginListener.lambda$onLogin$0(LoginListener.java:51)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:24:31] [SkinsRestorer Pool Thread #20560/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
[09:24:31] [SkinsRestorer Pool Thread #20560/INFO]: [SkinsRestorer] MySQL error: Duplicate entry '_crack' for key 'PRIMARY'
```

**Comment by DenisJ9798** [comment]
[https://sun9-31.userapi.com/impf/7KrgrttgLGOHewHVQO2Hb7ARPloQnlWd2zfYlg/SoXxmwKsHMk.jpg?size=1287x422&quality=96&proxy=1&sign=0cffc705e420152dd66f723c52f2264e](url) 
[https://sun9-19.userapi.com/impf/D--6GRpOlzNQmEE2cZIsrojCycCCH0bgBllprg/AqevBBZ1Nxg.jpg?size=538x169&quality=96&proxy=1&sign=bab06a7b5d498c84305df69e96b5acc3](url)

**Comment by xknat** [comment]
> [https://ibb.co/wNQym63](url)
> [https://ibb.co/7JJpdqK](url)

Can you upload to Imgur or pastebin?

**Comment by DenisJ9798** [comment]
> > [https://ibb.co/wNQym63](url)
> > [https://ibb.co/7JJpdqK](url)
> 
> Can you upload to Imgur or pastebin?

I made screenshots of the database with the given nickname, but how can I paste the information into pastebin?

**Comment by xknat** [comment]
> I made screenshots of the database with the given nickname, but how can I paste the information into pastebin?
imgur

**Comment by DenisJ9798** [comment]
[url=https://imgur.com/Yj1DAQo][img]http://i.imgur.com/Yj1DAQo.png[/img][/url]
[url=https://imgur.com/A05Nomx][img]http://i.imgur.com/A05Nomx.png[/img][/url]

**Comment by xknat** [comment]
@DenisJ9798 can you do the same for the other table?

**Comment by DenisJ9798** [comment]
Please clarify

**Comment by xknat** [comment]
@DenisJ9798 provide https://i.imgur.com/A05Nomx.png for SRPLAYER table

**Comment by xknat** [comment]
If not clear, join our discord. github is only for code / technical issues and not for player support.

**Comment by DenisJ9798** [comment]
> @DenisJ9798 provide https://i.imgur.com/A05Nomx.png for SRPLAYER table

see the first photo, this table does not have this nickname

**Comment by xknat** [comment]
> > @DenisJ9798 provide https://i.imgur.com/A05Nomx.png for SRPLAYER table
> 
> see the first photo, this table does not have this nickname

please provide uncropped. this way i can't factcheck.

**Comment by DenisJ9798** [comment]
> > > @DenisJ9798 provide https://i.imgur.com/A05Nomx.png for SRPLAYER table
> > 
> > 
> > see the first photo, this table does not have this nickname
> 
> please provide uncropped. this way i can't factcheck.

[img]https://i.imgur.com/hV35B6S.png[/img]

**Comment by xknat** [comment]
Please write or screenshot this part

![Uploading Screenshot_2020-11-28-18-01-53-865_com.android.chrome.jpg…]()

**Comment by xknat** [comment]
https://imgur.com/a/nv9aZGZ

**Comment by xknat** [comment]
@DenisJ9798 link = https://i.imgur.com/hV35B6S.png
@DenisJ9798 next time please provide image url and not embedded website

**Comment by xknat** [comment]
@DenisJ9798 looking from <https://i.imgur.com/hV35B6S.png>
i can not see if `_crack` is not in 'SRPlayers'
Please provide select ...      quiry
