### ISSUE TITLE
i am sorry, error 

### ISSUE THREAD

**Issue by mirikyoutube** [SkinsRestorer/SkinsRestorerX#382]
00:51:18 [WARNING] Error enabling plugin SkinsRestorer
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:305)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:37)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException
    at net.md_5.bungee.api.plugin.Plugin.getDataFolder(Plugin.java:61)
    at skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:36)
    ... 9 more

verison 13.8.7

**Comment by mirikyoutube** [comment]
fixed, sorry.
