### ISSUE TITLE
SkinsRestorerAPI will not work on spigot server under bungee mode.

### ISSUE THREAD

**Issue by khanghh** [SkinsRestorer/SkinsRestorerX#463]
## Describe the bug
The SkinStorage has not been initialized when running spigot server under bungee mode. It cause null pointer exception when calling SkinsRestorerAPI methods which reference to `skinStorage`

## Steps to reproduce the behavior
1. Running spigot server under bungee mode
2. Calling SkinsRestorerAPI methods

## Server information
* SkinsRestorer: 114.0.2
* Spigot version: 1.15.2
* Bungeecord version: #1549
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs 
```
java.lang.NullPointerException: null
        at net.skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:209) ~[?:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:149) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook$SkinsRestorerNew.getSkin(SkinsRestorerHook.java:69) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.setSkinTexture(SkinsRestorerHook.java:23) ~[?:?]
        at com.bgsoftware.superiorskyblock.hooks.SkinsRestorerHook.lambda$setSkinTexture$0(SkinsRestorerHook.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-391]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-391]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-391]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

```

**Comment by xknat** [comment]
Hey there @khanghh 
All commands, permissions, storage, config is done from bungee side.
The spigot one will go into listener to:
- open skins GUI
- apply the skin
