### ISSUE TITLE
Al entrar un jugador aparece el siguiente error

### ISSUE THREAD

**Issue by BautistaIza** [SkinsRestorer/SkinsRestorerX#521]
Al entrar un jugador aparece el siguiente error
When a player enters the following error appears

[SkinsRestorer] Task #4853 for SkinsRestorer v14.0.2 generated an exception
java.lang.NoSuchMethodError: 'us.myles.ViaVersion.ViaManager us.myles.ViaVersion.api.Via.getManager()'
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:279) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:50) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.lambda$updateSkin$1(UniversalSkinFactory.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-600]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-600]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-600]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-600]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-600]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-600]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-600]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by 4drian3d** [comment]
Actualiza SkinsRestorer
Update SkinsRestorer
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/43/artifact/target/SkinsRestorer.jar

**Comment by xknat** [comment]
github is english only. please do never post non english ticket.
