### ISSUE TITLE
MASSIVE 1.16 issue!

### ISSUE THREAD

**Issue by AirCraze** [SkinsRestorer/SkinsRestorerX#541]
## Describe the bug
ViaVersion issue
## How can we reproduce what you got?
[15:07:31 WARN]: [SkinsRestorer] Task #2136 for SkinsRestorer v14.0.2 generated an exception
java.lang.NoSuchMethodError: 'us.myles.ViaVersion.ViaManager us.myles.ViaVersion.api.Via.getManager()'
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:279) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:50) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.lambda$updateSkin$1(UniversalSkinFactory.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1169]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1169]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1169]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1169]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1169]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1169]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1169]
        at java.lang.Thread.run(Thread.java:831) [?:?]
**Expected behavior**
Load your skin
**Screenshots**

## Server information
Happens when a player joins
**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: latest
* Spigot version: 1.16.5
* Bungeecord version: 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 16
* plugin list bungee & spigot: 
* MinecraftLauncher?: 
* if multiverse, (censored) worlds file: 

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

**Comment by xknat** [comment]
Github only support latest dev build right now
