### ISSUE TITLE
defaultskins issue with url skins

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#571]
from spigotmc: https://www.spigotmc.org/conversations/skinsrestorer-bug.465680/
Hello, SRTeam.
I encountered a bug using skinsrestorer,

Enable this feature when I modify the configuration file config.yml:

DefaultSkins:
Enabled: true

Then enter the server and the console reports an error:
[17:40:30 WARN]: [SkinsRestorer] Plugin SkinsRestorer v14.1.1 generated an exception while executing task 424
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "skinType" is null
at net.skinsrestorer.shared.utils.connections.MineSkinAPI.genSkin(MineSkinAPI.java:71) ~[?:?]
at net.skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:58) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-66]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-66]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-66]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

The player's default skin has not been changed.

mc server version: paper-1.17-66.jar
MC version: 1.17
plugin version: 14.1.1

**Comment by xknat** [comment]
resolved in DEV 82: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/82/artifact/target/SkinsRestorer.jar
