### ISSUE TITLE
The plugin Dont create any folder and i cant see my skin

### ISSUE THREAD

**Issue by Hugytor09YT** [SkinsRestorer/SkinsRestorerX#577]
## Describe the bug
I cant see my skin and the plugin dont create any folder plugin.

## How can we reproduce what you got?
1. Start the server and join with a premium account.

**Expected behavior**

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**
* SkinsRestorer: Lastet
* Spigot version: PaperSpigot 1.7.10
* Bungeecord version: None 
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 8
* plugin list bungee & spigot: HCF classic plugins (Lazarus and AquaCore)
* MinecraftLauncher?: Premium Launcher (Classic)
* if multiverse, (censored) worlds file: No multiverse used

## Logs
Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs from **Bungeecord *AND* Spigot/Bukkit**)
[08:03:34 WARN]: java.io.IOException: No such file or directory
[08:03:34 WARN]:        at java.io.UnixFileSystem.createFileExclusively(Native Method)
[08:03:34 WARN]:        at java.io.File.createNewFile(File.java:1014)
[08:03:34 WARN]:        at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:394)
[08:03:34 WARN]:        at skinsrestorer.shared.storage.SkinStorage.setSkinData(SkinStorage.java:407)
[08:03:34 WARN]:        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:131)
[08:03:34 WARN]:        at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:145)
[08:03:34 WARN]:        at skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:47)
[08:03:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[08:03:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:03:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:03:34 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:03:34 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:03:34 WARN]: java.lang.NullPointerException
[08:03:34 WARN]:        at skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:76)
[08:03:34 WARN]:        at skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:17)
[08:03:34 WARN]:        at skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.lambda$updateSkin$0(UniversalSkinFactory.java:37)
[08:03:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[08:03:34 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[08:03:34 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:705)
[08:03:34 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307)
[08:03:34 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:646)
[08:03:34 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:551)
[08:03:34 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by xknat** [comment]
1.7.10 is not a supported version.
