### ISSUE TITLE
velocity error "because the return value of getSkinApplierVelocity() is null"

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#605]
https://discord.com/channels/186794372468178944/186794372468178944/873477339672113184

[16:00:10 ERROR]: Couldn't pass GameProfileRequestEvent to skinsrestorer
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.velocity.SkinApplierVelocity.updateProfileSkin(com.velocitypowered.api.util.GameProfile, String)" because the return value of "net.skinsrestorer.velocity.SkinsRestorer.getSkinApplierVelocity()" is null
        at net.skinsrestorer.velocity.listener.GameProfileRequest.onGameProfileRequest(GameProfileRequest.java:56) ~[?:?]
        at net.skinsrestorer.velocity.listener.Lmbda$43.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:587) ~[velocity-3.0.0.jar:3.0.0]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$6(VelocityEventManager.java:468) ~[velocity-3.0.0.jar:3.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by AlexProgrammerDE** [comment]
The real issue is hidden because an error n the initialization of the config/commands failed.  Linked PR will initialize everything in a safe environment earlier.
