### ISSUE TITLE
Defaultskinserror when the default custom skin is not present as a skin file

### ISSUE THREAD

**Issue by download042** [SkinsRestorer/SkinsRestorerX#624]
DEV notes:
Error when only default skin gets removed
```
[17:52:13] [Craft Scheduler Thread - 2/WARN]: [SkinsRestorer] [WARNING] DefaultSkin 'test_RT' could not be found or requested! Removing from list..
[17:52:35] [Craft Scheduler Thread - 4/WARN]: [SkinsRestorer] Plugin SkinsRestorer v14.1.3 generated an exception while executing task 356
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorage.getDefaultSkinName(SkinStorage.java:647) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorage.getDefaultSkinName(SkinStorage.java:607) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:52) ~[SkinsRestorer.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-172]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

```

-------
There is a console error when a player joins to the server.

PaperSpigot 1.16.5
* SkinsRestorer: 14.1.3
* Java: 11.0.11
* plugin list spigot: 
![image](https://user-images.githubusercontent.com/13710574/129721844-3465c460-58b7-4f34-9478-739a58e544a5.png)

## Logs
https://pastebin.com/D8j96tSx

**Comment by xknat** [comment]
@download042 skinsrestorer config?
what is your default skins skin file?

**Comment by download042** [comment]
@xknat 
my config: https://pastebin.com/uQVMYvh2

> #what is your default skins skin file?
What do you mean?

**Comment by xknat** [comment]
> @xknat
> my config: https://pastebin.com/uQVMYvh2
> 
> > #what is your default skins skin file?
> > What do you mean?

you did enable 
```
DefaultSkins:
  Enabled: true
```
with the name "teszt"
can i see "teszt" skin file?

**Comment by download042** [comment]
I have no file with such name. Should it be?

**Comment by xknat** [comment]
> I have no file with such name. Should it be?

well, there is your issue...
you can only enable the default skin if you have the skin file

**Comment by download042** [comment]
Aight, thanks man!

**Comment by xknat** [comment]
can confirm:
```
[17:52:13] [Craft Scheduler Thread - 2/WARN]: [SkinsRestorer] [WARNING] DefaultSkin 'test_RT' could not be found or requested! Removing from list..
[17:52:35] [Craft Scheduler Thread - 4/WARN]: [SkinsRestorer] Plugin SkinsRestorer v14.1.3 generated an exception while executing task 356
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.skinsrestorer.shared.storage.SkinStorage.getDefaultSkinName(SkinStorage.java:647) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.shared.storage.SkinStorage.getDefaultSkinName(SkinStorage.java:607) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.listener.PlayerJoin.lambda$onJoin$0(PlayerJoin.java:52) ~[SkinsRestorer.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-172]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
