### ISSUE TITLE
New version of Skinsrestorer incompatibility - PaperSkinRefresher (paper 1.11.2)

### ISSUE THREAD

**Issue by revkilleri** [SkinsRestorer/SkinsRestorerX#655]
## Describe the bug

We used skins restorer without problems for many months, unfortunately after the last automatic updates the plugin stopped working. 

## How can we reproduce what you got?
Combination of paper (Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)) and last versions of SkinsRestorer

**Expected behavior**
Updated method PaperSkinRefresher. The old version of the skinsrestorer worked perfectly fine two months ago. (We have been using your great plugin for many months)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**
Paper

**What version? Do NOT answer LATEST**
* SkinsRestorer: SkinsRestorer v14.1.4-SNAPSHOT
* Paper version: Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

## Logs
[12:45:57] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.4-SNAPSHOT
[12:45:57] [Server thread/INFO]: [0;33;1m[[0;32;22mSkinsRestorer[0;33;1m] [mFailed PaperSkinRefresher[m
[12:45:57] [Server thread/ERROR]: §e[§2SkinsRestorer§e] §r§c§nCould not initialize SkinApplier! Please report this on our discord server! 
net.skinsrestorer.shared.exception.InitializeException: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.refreshPlayer()
	at net.skinsrestorer.bukkit.skinrefresher.PaperSkinRefresher.<init>(PaperSkinRefresher.java:53) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinApplierBukkit.detectRefresh(SkinApplierBukkit.java:70) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinApplierBukkit.<init>(SkinApplierBukkit.java:54) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:123) [SkinsRestorer.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.refreshPlayer()
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_152]
	at net.skinsrestorer.bukkit.skinrefresher.PaperSkinRefresher.<init>(PaperSkinRefresher.java:38) ~[SkinsRestorer.jar:?]
	... 14 more
[12:45:57] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v14.1.4-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:128) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[12:45:57] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v14.1.4-SNAPSHOT

## Additional context

An older version of the skins restorer, which will not update itself, can also solve our situation. This plugin has meant a lot to us for many months and many players are missing it. I am an RPG server running on version 1.11.2 paper and therefore compatibility with this version is very important to us.

**Comment by xknat** [comment]
@revkilleri should be resolved in dev build

**Comment by revkilleri** [comment]
> should be resolved in dev build

It would be great! :)

**Comment by revkilleri** [comment]
It seems that the dev version already works great. Great job! Thank you!
