### ISSUE TITLE
14.1.4 caused SQL Exception

### ISSUE THREAD

**Issue by nhanledev** [SkinsRestorer/SkinsRestorerX#673]
## Describe the bug

The plugin caused `net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException`

## How can we reproduce what you got?

1. Setup a BungeeCord server with AdvancedBan using MySQL
2. Get 14.1.4 version from `https://github.com/SkinsRestorer/SkinsRestorerX/releases/tag/14.1.4`
2. Setup this plugin to run using MySQL
3. See the error

`[05:21:08 ERROR] [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Exception during pool initialization.
java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: net.skinsrestorer.shadow.com.mysql.cj.exceptions.WrongArgumentException: Can't instantiate required class
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:131) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37) ~[?:?]
        at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51) ~[?:?]
        at me.leoko.advancedban.Universal.setup(Universal.java:72) ~[?:?]
        at me.leoko.advancedban.bungee.BungeeMain.onEnable(BungeeMain.java:32) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
Caused by: net.skinsrestorer.shadow.com.mysql.cj.exceptions.UnableToConnectException: Cannot load connection class because of underlying exception: net.skinsrestorer.shadow.com.mysql.cj.exceptions.WrongArgumentException: Can't instantiate required class
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        ... 16 more
Caused by: net.skinsrestorer.shadow.com.mysql.cj.exceptions.WrongArgumentException: Can't instantiate required class
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.util.Util.getInstance(Util.java:169) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.util.Util.getInstance(Util.java:174) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl$Type.getImplementingInstance(ConnectionUrl.java:241) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl$Type.getConnectionUrlInstance(ConnectionUrl.java:211) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:280) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:195) ~[?:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.skinsrestorer.shadow.com.mysql.cj.conf.url.SingleConnectionUrl
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:1698972:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.util.Util.getInstance(Util.java:167) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.util.Util.getInstance(Util.java:174) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl$Type.getImplementingInstance(ConnectionUrl.java:241) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl$Type.getConnectionUrlInstance(ConnectionUrl.java:211) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:280) ~[?:?]
        at net.skinsrestorer.shadow.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:195) ~[?:?]
        ... 15 more`

**Expected behavior**
Load along with other plugins normally as of `14.1.4`

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

Bungeecord

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.4
* Spigot version:
* Bungeecord version: Waterfal Build 449
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8
* plugin list bungee & spigot:
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

## Additional context

The earlier version `14.1.3` ran normally on my BungeeCord server. After updating `14.1.4`, the server starts to throw SQL related exception. The earlier JAR file size is over 6MB, but `14.1.4` is only over 4 MB. I think something might be missing in this update.

**Comment by xknat** [comment]
@nhanledev hey there!
can you join our discord?
we got a version to test out for you ;) ^

**Comment by nhanledev** [comment]
Hello,

I joined your Discord server, and with put a feedback here after finishing the test.
