### ISSUE TITLE
SkinsRestorer 14.1.4 not working on Velocity

### ISSUE THREAD

**Issue by Xen0Xys** [SkinsRestorer/SkinsRestorerX#674]
## Describe the bug

SkinsRestorer not support Velocity in 14.1.4

## How can we reproduce what you got?

Put 14.1.4 SkinsRestorer Jar in velocity plugin folder

**Expected behavior**

Skinsrestorer working on Velocity

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

Velocity with the following logs:
```
[08:54:14 ERROR]: Unable to load plugin plugins/SkinsRestorer.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file SkinsRestorer.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPluginDescription(JavaPluginLoader.java:61) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:93) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:325) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:223) ~[velocity.jar:3.0.0]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.0.0]
```

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.4
* Velocity version: 3.0.0
* Java: 16

## Additional context

See that velocity_plugin.json file not exist in SkinsRestorer.jar

**Comment by AlexProgrammerDE** [comment]
Fixed by #675
