### ISSUE TITLE
MC 1.18 Support

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#736]
We are working hard on supporting 1.18 we will give updates on our discord server.

**Known Errors** 
These errors will appear when using mc 1.18 & SkinsRestorer:
```
net.skinsrestorer.api.reflection.exception.ReflectionException: java.lang.NoSuchMethodException: 
net.minecraft.server.level.EntityPlayer.getProfile()
```
```
net.skinsrestorer.api.reflection.exception.ReflectionException: java.lang.NoSuchMethodException: 
net.minecraft.server.level.EntityPlayer.getWorld()
```

**Comment by ElnuDev** [comment]
> paper may work just fine or differently

It's not working on paper 1.18 build 10 either for me. In the logs, I'm getting `java.lang.NoSuchMethodException` for both `net.minecraft.server.level.EntityPlayer.triggerHealthUpdate()` at server startup and `net.minecraft.server.level.EntityPlayer.getProfile()`.

**Comment by xknat** [comment]
> > paper may work just fine or differently
> 
> It's not working on paper 1.18 build 10 either for me. In the logs, I'm getting `java.lang.NoSuchMethodException` for both `net.minecraft.server.level.EntityPlayer.triggerHealthUpdate()` at server startup and `net.minecraft.server.level.EntityPlayer.getProfile()`.

Likely because your using viaversion or protocolhack which forces you to the spigot one

**Comment by ElnuDev** [comment]
Viaversion? Protocolhack? I'm not running any of these, at least not knowingly. I haven't ever heard of them (sorry for my ignorance, I only really got into server hosting stuff recently)

**Comment by qyl27** [comment]
It seems that the problem caused by the spigot had removed the mapping of method names, and the paper is not working either.
More detailed, after the exception `net.skinsrestorer.shared.exception.InitializeException: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.triggerHealthUpdate()`, SkinsRestorer will use SpigotSkinRefresher instead, then same with on spigot.

**Comment by AlexProgrammerDE** [comment]
> > > paper may work just fine or differently
> > 
> > It's not working on paper 1.18 build 10 either for me. In the logs, I'm getting `java.lang.NoSuchMethodException` for both `net.minecraft.server.level.EntityPlayer.triggerHealthUpdate()` at server startup and `net.minecraft.server.level.EntityPlayer.getProfile()`.
> 
> Likely because your using viaversion or protocolhack which forces you to the spigot one

Actually no. That method gets even executed before we use one of our refreshers.

**Comment by AlexProgrammerDE** [comment]
> It seems that the problem caused by the spigot had removed the mapping of method names, and the paper is not working either.
> More detailed, after the exception `net.skinsrestorer.shared.exception.InitializeException: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.triggerHealthUpdate()`, SkinsRestorer will use SpigotSkinRefresher instead, then same with on spigot.

As a last option we can probably start using mojang/spigot mappings and make one implementation per mapping version.

**Comment by adamo0917** [comment]
this will be useful, because i have 1.18 SMP and i don't want to use ViaVersion or something.

**Comment by NoniDOTio** [comment]
This is the full error I'm getting when a player connects to my paper-1.18-39 server with the latest ViaVersion:
`[17:27:26 WARN]: net.skinsrestorer.api.reflection.exception.ReflectionException: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.getProfile()
[17:27:26 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.api.reflection.ReflectionUtil.invokeMethod(ReflectionUtil.java:270)
[17:27:26 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.bukkit.SkinApplierBukkit.lambda$applySkin$1(SkinApplierBukkit.java:109)
[17:27:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:27:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:27:26 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[17:27:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[17:27:26 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[17:27:26 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[17:27:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[17:27:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:27:26 WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.level.EntityPlayer.getProfile()
[17:27:26 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[17:27:26 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.api.reflection.ReflectionUtil.getMethod(ReflectionUtil.java:130)
[17:27:26 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.api.reflection.ReflectionUtil.invokeMethod(ReflectionUtil.java:268)
[17:27:26 WARN]:        ... 9 more`

**Comment by xknat** [comment]
Resolved by https://github.com/SkinsRestorer/SkinsRestorerX/pull/749
