### ISSUE TITLE
Emoji in skin will not work for mysql

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#828]
[19:34:44] [Netty Worker IO Thread #0/INFO]: player executed command: /skin AfterChange🍸
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x8D\xB8' for column 'Skin' at row 1
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at net.skinsrestorer.shared.storage.MySQL.execute(MySQL.java:120)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at net.skinsrestorer.shared.storage.SkinStorage.setSkinName(SkinStorage.java:352)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at net.skinsrestorer.bungee.commands.SkinCommand.setSkin(SkinCommand.java:282)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at net.skinsrestorer.bungee.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:191)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:34:44] [SkinsRestorer Pool Thread #4751/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
[19:34:44] [SkinsRestorer Pool Thread #4751/WARN]: [SkinsRestorer] MySQL error: Incorrect string value: '\xF0\x9F\x8D\xB8' for column 'Skin' at row 1

**Comment by xknat** [comment]
Feature dropped
