### ISSUE TITLE
Travertine can't get NMS Version

### ISSUE THREAD

**Issue by xknat** [SkinsRestorer/SkinsRestorerX#849]
[17:35:27 WARN]: Exception encountered when loading plugin: SkinsRestorer
java.lang.ExceptionInInitializerError: null
        at net.skinsrestorer.shared.utils.SharedMethods.allowIllegalACFNames(SharedMethods.java:41) ~[?:?]
        at net.skinsrestorer.shared.interfaces.ISRPlugin.prepareACF(ISRPlugin.java:58) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.initCommands(SkinsRestorer.java:138) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:120) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.18-R0.1-SNAPSHOT:a8db942:unknown]
        at net.md_5.bungee.BungeeCord.start(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.18-R0.1-SNAPSHOT:a8db942:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.18-R0.1-SNAPSHOT:a8db942:unknown]
        at net.md_5.bungee.Bootstrap.main(Unknown Source) ~[server.jar:git:Travertine-Bootstrap:1.18-R0.1-SNAPSHOT:a8db942:unknown]
Caused by: java.lang.NullPointerException
        at net.skinsrestorer.api.serverinfo.ServerVersion.getNMSVersion(ServerVersion.java:42) ~[?:?]
        at net.skinsrestorer.api.reflection.ReflectionUtil.<clinit>(ReflectionUtil.java:36) ~[?:?]
        ... 8 more

**Comment by xknat** [comment]
Travertine now loads (1.16-178)
