### ISSUE TITLE
MySQL connnection problem: No suitable driver found for jdbc:mysql://...

### ISSUE THREAD

**Issue by vitaly-rudenko** [SkinsRestorer/SkinsRestorerX#939]
## Describe the bug

SkinsRestorer can't connect to the MySQL database on a Velocity proxy server.

## How can we reproduce what you got?

1. Setup SkinsRestorer,
2. Configure MySQL connection,
3. Start the Velocity server.

**Expected behavior**
SkinsRestorer should start successfully.

## Server information

On what platform does your server run: **Paper server, Velocity proxy**

* SkinsRestorer: **14.1.15**
* Velocity version: **3.1.1-98 (stable)**
* IF bungee, did you put the plugin on all servers: **Yes**
* Java: **17**
* plugin list bungee & spigot: **no plugins on bungee except for SkinsRestorer**
* Database: **MySQL 5.7**

## Logs

```
[18:08:33 INFO] [skinsrestorer]: Can't connect to MySQL! Disabling SkinsRestorer.
java.sql.SQLException: No suitable driver found for jdbc:mysql://mysql:3306/skinsrestorer?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
	at java.sql.DriverManager.getConnection(DriverManager.java:706) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:229) ~[java.sql:?]
	at net.skinsrestorer.shared.storage.MySQL.openConnection(MySQL.java:64) ~[?:?]
	at net.skinsrestorer.shared.utils.SharedMethods.initMysql(SharedMethods.java:75) ~[?:?]
	at net.skinsrestorer.velocity.SkinsRestorer.initStorage(SkinsRestorer.java:155) ~[?:?]
	at net.skinsrestorer.velocity.SkinsRestorer.onProxyInitialize(SkinsRestorer.java:129) ~[?:?]
	at net.skinsrestorer.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.1-98.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.1-98.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:08:33 INFO]: Listening on /0.0.0.0:25577
[18:08:33 INFO]: Listening for GS4 query on /0.0.0.0:25577
[2022-05-18T18:08:33.754Z] [INFO]: [MinecraftRunner] Minecraft has started
[18:08:33 INFO]: Done (5.08s)!
velocity version
[18:08:52 INFO]: Velocity 3.1.1
[18:08:52 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[18:08:52 INFO]: velocitypowered.com - GitHub
```

## Additional context

Worked just fine on a Paper server (without Velocity proxy).

**Comment by xknat** [comment]
@vitaly-rudenko can you try dev build number 319:
https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/319/artifact/build/libs/SkinsRestorer.jar

**Comment by vitaly-rudenko** [comment]
Seems to connect successfully, but there is some SQL syntax error:
```
[2022-05-18T18:34:17.972Z] [INFO]: [skinsrestorer] Connected to MySQL!
[2022-05-18T18:34:18.001Z] [WARN]: [net.skinsrestorer.shadow.mariadb.message.server.ErrorPacket] Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `timestamp` text COLLATE utf8_unicode_ci' at line 1
[2022-05-18T18:34:18.002Z] [ERROR]: java.sql.SQLSyntaxErrorException: (conn=15) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `timestamp` text COLLATE utf8_unicode_ci' at line 1
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.export.ExceptionFactory.createException(ExceptionFactory.java:270)
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.export.ExceptionFactory.create(ExceptionFactory.java:358)
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.message.ClientMessage.readPacket(ClientMessage.java:133)
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.readPacket(StandardClient.java:815)
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.readResults(StandardClient.java:754)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.readResponse(StandardClient.java:673)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.client.impl.StandardClient.execute(StandardClient.java:616)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.ClientPreparedStatement.execute(ClientPreparedStatement.java:256)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shared.storage.MySQL.execute(MySQL.java:79)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shared.storage.MySQL.createTable(MySQL.java:59)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.shared.utils.SharedMethods.initMysql(SharedMethods.java:77)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.velocity.SkinsRestorer.initStorage(SkinsRestorer.java:155)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.velocity.SkinsRestorer.onProxyInitialize(SkinsRestorer.java:129)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at net.skinsrestorer.velocity.Lmbda$1.execute(Unknown Source)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2022-05-18T18:34:18.004Z] [ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[2022-05-18T18:34:18.004Z] [WARN]: [skinsrestorer] MySQL error: (conn=15) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `timestamp` text COLLATE utf8_unicode_ci' at line 1
[2022-05-18T18:34:18.068Z] [INFO]: [skinsrestorer] Enabled SkinsRestorer v14.2.0-SNAPSHOT
```

I'm investigating if that's a problem on my side. I've created the database like this:
```
CREATE DATABASE IF NOT EXISTS skinsrestorer CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL ON `skinsrestorer`.* TO 'user'@'%';
```

**Comment by xknat** [comment]
> [2022-05-18T18:34:18.002Z] [ERROR]: java.sql.SQLSyntaxErrorException: (conn=15) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `timestamp` text COLLATE utf8_unicode_ci' at line 1
[2022-05-18T18:34:18.003Z] [ERROR]: 	at net.skinsrestorer.shadow.mariadb.export.ExceptionFactory.createException(ExceptionFactory.java:270)

likely because of https://github.com/SkinsRestorer/SkinsRestorerX/commit/c298555db38fdf93b966f763b2c8bfdc943afb54#diff-d6b48bbac472e63ebc7b94a0364353a1cfb5538e932ee7b6bde63b33965ff573R59

**Comment by vitaly-rudenko** [comment]
I guess MySQL, at least 5.7, does not support this syntax :(

**Comment by AlexProgrammerDE** [comment]
Yup it should be fixed in https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/332/artifact/build/libs/SkinsRestorer.jar
