### ISSUE TITLE
BungeeCord 1.19 support

### ISSUE THREAD

**Issue by linsaftw** [SkinsRestorer/SkinsRestorerX#956]
Error on startup in new BungeeCord 1.19

```
[20:42:05 WARN]: Error loading plugin SkinsRestorer
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:341) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
        at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:67) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:72) ~[?:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:7c38e1d:unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
        at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:67) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:72) ~[?:?]
        ... 10 more
```

**Comment by nhanledev** [comment]
hello linsa, just build your latest version of FlameCord and get this error too
This error also happen on 1.19 public beta test version of SkinsRestorer

**Comment by MorkaZ** [comment]
Will it be fixed in near future?

**Comment by xknat** [comment]
We made a release that support 1.19 bungee on our discord in `#1-19-public-testing`
This one will work for ONLY 1.19 bungee.

**Comment by linsaftw** [comment]
AWESOME!

**Comment by xknat** [comment]
This has now been merged to our dev builds which you can find on https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/
