### ISSUE TITLE
SkinRestorerX (latest dev version) does not work with latest Waterfall (paper bungee fork)

### ISSUE THREAD

**Issue by MorkaZ** [SkinsRestorer/SkinsRestorerX#963]
https://pastebin.com/AjGzVVST

**Comment by MorkaZ** [comment]
text block (missing classes):
```[11:41:33] [main/WARN]: Error loading plugin SkinsRestorer
[11:41:33] [main/WARN]: Error loading plugin SkinsRestorer
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
	at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:69) ~[?:?]
	at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:73) ~[?:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall-0-1.19-PaperMC.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
	at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:69) ~[?:?]
	at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:73) ~[?:?]
	... 10 more```

**Comment by arturek1666** [comment]
This was already reported here:
https://github.com/SkinsRestorer/SkinsRestorerX/issues/956

**Comment by xknat** [comment]
^
