### ISSUE TITLE
Bungeecord code changes 

### ISSUE THREAD

**Issue by MossCG** [SkinsRestorer/SkinsRestorerX#973]
## Describe the bug

I updated my waterfall from 488 to 496, and an exception was appeared.
you can see changes from bungeecord's commits:

https://github.com/SpigotMC/BungeeCord/commit/eccdf87f2217ae3a0f6943134d8c61df3f9d0097?diff=split#diff-7c3f50add43fe2b0cd700cf1d2a47e5fa0bb5d0045693477331c77196f442180

net.md_5.bungee.connection.LoginResult$Property was removed
stacktraces:
[21:06:41 WARN]: Error loading plugin SkinsRestorer
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_261]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
        at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:67) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:72) ~[?:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_261]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_261]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29) ~[?:?]
        at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:67) ~[?:?]
        at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:72) ~[?:?]
        ... 9 more

## How can we reproduce what you got?

1.use the lastes waterfall (My version is 496)
2.add this plugin to the plugin folder
3.run ,and you will see the error

**Expected behavior**

**Screenshots**

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer:  LATEST
* Spigot version: /
* Bungeecord version: LATEST
* IF bungee, did you put the plugin on all servers:  No
* Java: 18
* plugin list bungee & spigot: /
* MinecraftLauncher?: /
* if multiverse, (censored) worlds file: /

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://gist.github.com
https://hastebin.app

**Comment by AlexProgrammerDE** [comment]
The issue is well known and already fixed. Either wait for the next release or join our discord server and download the latest dev build.
