### ISSUE TITLE
Bungee Error

### ISSUE THREAD

**Issue by Y3ko** [SkinsRestorer/SkinsRestorerX#98]
### Describe the problem in a few short sentences
[21:31:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@724f138e, id=13, owner=skinsrestorer.bungee.SkinsRestorer@58f07f02, task=skinsrestorer.bungee.listeners.LoginListener$1@1d667bc4, delay=0, period=0, running=true) encountered an exception
java.lang.IllegalStateException: Plugin skinsrestorer.bungee.SkinsRestorer@58f07f02 has not registered intent for event LoginEvent(cancelled=true, cancelReasonComponents=[TextComponent{text=Sunucuda su an bakim ve yenilik calismalari yapilmakta!, BaseComponent(color=§f, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)}], loginResult=null, connection=[/85.103.152.255:53330|XboyHD] <-> InitialHandler)
        at com.google.common.base.Preconditions.checkState(Preconditions.java:721) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
        at net.md_5.bungee.api.event.AsyncEvent.completeIntent(AsyncEvent.java:68) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
        at skinsrestorer.bungee.listeners.LoginListener$1.run(LoginListener.java:75) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:17e4f19:219]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

### What version of SkinsRestorerX are you using?
Exact Version: 13.5
### What is your Spigot/BungeeCord/Sponge version?
Waterfall Lastest

**Comment by McLive** [comment]
Please try again with the most recent build on [Jenkins ](https://ci.freecraft.eu/v2/job/SkinsRestorerX/) and if the error still exists, send new error messages.

**Comment by McLive** [comment]
Please open a new issue if the error still happens.
