### ISSUE TITLE
PaperMC 1.19 can't load SkinsRestorer.jar on start

### ISSUE THREAD

**Issue by theqa-ninja** [SkinsRestorer/SkinsRestorerX#986]
## Describe the bug

Unable to load SkinRestorer on Paper MC server

## How can we reproduce what you got?

1. Have MC vanillia running on Paper as version 1.19
2. navigate to the minecraft/plugins folder
3. ran `wget -o SkinsRestorer.jar https://www.spigotmc.org/resources/skinsrestorer.2124/download?version=457289`
4. ran `chmod 755 SkinsRestorer.jar`
5. restarted the server
6. failed to load SkinRestorer

## Server information

* PaperMC 1.19-31.jar
* SkinsRestorer: 14.2.1
* openjdk: 17.0.3 2022-04-19
* plugin nothing else

## Logs

```
[09:52:50 INFO]: Starting Minecraft server on *:25565
[09:52:50 INFO]: Using epoll channel type
[09:52:50 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[09:52:50 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[09:52:51 ERROR]: Could not load 'plugins/SkinsRestorer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:154) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:412) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 6 more
```

**Comment by xknat** [comment]
your zip file is corrupt, not skinsrestorer issue `java.util.zip.ZipException: zip END header not found`

**Comment by xknat** [comment]
btw, we have a build in updater

**Comment by theqa-ninja** [comment]
hmm... weird, why is wget giving me a corrupt zip >_<.  Seems like a valid link when I download it normally and check it on my PC

**Comment by theqa-ninja** [comment]
very odd, yeah, i downloaded the file from the same link and copied to the box it worked fine.  Thanks @xknat !
