### ISSUE TITLE
Trmenu cannot call the API normally

### ISSUE THREAD

**Issue by MuMuMuCODE** [SkinsRestorer/SkinsRestorerX#989]
[16:54:50 WARN]: [TrMenu] Plugin TrMenu v3.1.12 generated an exception while executing task 34699
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292) ~[SkinsRestorer14.2.1.jar:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268) ~[SkinsRestorer14.2.1.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114) ~[SkinsRestorer14.2.1.jar:?]
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:26) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.1.12.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by xknat** [comment]
not a bug, api cant be used on backend while in proxy mode
